### ISSUE TITLE
Handle HTML-only mail

### ISSUE THREAD

**Issue by 5long** [sup-heliotrope/sup#101]
Some mail senders (rushed-out in-house services, accessibility-unaware tech startups not using 3rd-party mail services) only send email in HTML format without providing plain-text alternative.

Sup might need to handle this for a better user experience. If so, a few things come to mind:
- Still prefer plain-text if possible
- Parse and strip HTML tag soup for indexing
- Parse and strip HTML tag soup for displaying
  - Is there a good way to display `<a>`? The `href` attribute is no doubt important. But how to present it to user?
  - What about `<img>`? `<table>`? Shall we implement an HTML render engine? (short answer: probably no.)
- An HTML parser is needed. In the Ruby world this might imply Nokogiri, which requires libxml and friends as new dependencies.

**Comment by inktrap** [comment]
Just a quick reminder, w3m can number links:
~~~
require 'shellwords'
unless sibling_types.member? "text/plain"
  case content_type
  when "text/html"
    `/usr/bin/w3m -o display_link_number=1 -dump -T #{content_type} #{Shellwords.escape filename}`
  end
end
~~~

**Comment by ppwwyyxx** [comment]
When there are both text/plain and text/html available, sup will display them both. Is there a way to only display one of them? Also, is there any way to let sup prefer HTML mime-decode instead of text/plain?
because w3m dumps usually look better than plain text.
