### ISSUE TITLE
Multible postpones hides draft message

### ISSUE THREAD

**Issue by asalminen** [sup-heliotrope/sup#230]
Doing several postpones and continues for message did cause message to disappear. Could not find message anywhere or with search all messages. 

Steps to reproduce:

1. Compose new message
2. Add to: and Subject 
3. Postpone 
4. Edit postpone message adding some text
5. Postpone 

Result: Message disappear from drafts and all other locations. Message did reappear later after restarting sup to drafts.

sup v0.15.2

Update:
Able to reproduce with v0.15.4 with one extra postpone edit loop.

**Comment by gauteh** [comment]
Presumably fixed in #435.
