### ISSUE TITLE
output stalls unless user refreshes (ctrl-l)

### ISSUE THREAD

**Issue by eMBee** [sup-heliotrope/sup#248]
i am still investigating this, trying different ncurses versions, but i am reporting it incase someone else has seen that and has an idea:

sup seems to stall waiting for me to refresh the screen before it outputs anything. i'll investigate some more though (like building the gem for ncueses 5.9 properly and also looking into applying the fedora or debian patches to ncurses 5.9 to see if they make that problem go away)

this happens only on the debian 6 (squeeze) machine, but not on fedora (which also has ncurses 5.9, but with some patches applied)

**Comment by gauteh** [comment]
need info, possibly fixed.
