### ISSUE TITLE
sup-tweak-labels does not correctly parse query when removing labels

### ISSUE THREAD

**Issue by avtobiff** [sup-heliotrope/sup#336]
From the Debian bug report https://bugs.debian.org/764315

    Hello I tried to use sup-tweak-labels to modify in bunch the labels of
    some mailing list that I had imported with the following command:

       sup-tweak-labels -e --all-sources -n -r inbox -q "label:ML"

    Unfortunately it crashed with the following traceback:

       /usr/lib/ruby/vendor_ruby/sup/index.rb:531:in `parse_query':
       Redwood::Index::ParseError (Redwood::Index::ParseError)
           from /usr/bin/sup-tweak-labels:88:in `<main>'

    A quick glance at the code shows that I should have use "AND
    label:ML". And indeed it worked but it is quite counterintuitive.

    I suggest to automatically add the 'AND' in the line 140 of
    /usr/bin/sup-tweak-labels when opts[:query] (but it's the first time
    that I read ruby code so there might be a better fix).

**Comment by gauteh** [comment]
Fixed.
