### ISSUE TITLE
Archive all mails

### ISSUE THREAD

**Issue by nanooq** [sup-heliotrope/sup#385]
How do I archive all mails in inbox?

**Comment by rakoo** [comment]
Excerpts from Nanooq's message of 2015-01-19 19:23:05 +0100:
> How do I archive all mails in inbox?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sup-heliotrope/sup/issues/385

0. Go to the inbox view
1. Tag all mails with 'T'
2. Start an "action on all tagged threads" with '='
3. Select the action, here you want to archive so it's 'a'

-- 
Matthieu Rakotojaona
