### ISSUE TITLE
sup hangs up on encryt, then crashes on interrupt

### ISSUE THREAD

**Issue by FiskerLars** [sup-heliotrope/sup#386]
Hi, 
running 
gpg (GnuPG) 2.1.1
libgcrypt 1.6.2

I have the strange effect that sup hangs up during encryption (no signature) of any email. I am not able to figure out what is happening there. 

While sup correctly realises that we are on GnuPG 2, it hangs up during encryption (simply not returns from 
cipher = crypto.encrypt(format_payload(payload), gpg_opts).read

Current (insecure) parameters just before are
cipher {:protocol=>0, :armor=>true, :textmode=>true, :always_trust=>true, :recipients=>["XXX@xxx", "XXX2@xxx"]}

The GPG_TTY variable is set.

The exceptional output is:
--- Interrupt from thread: main

/usr/lib/ruby/gems/2.2.0/gems/gpgme-2.0.8/lib/gpgme.rb:35:in `error_to_exception'
/usr/lib/ruby/gems/2.2.0/gems/gpgme-2.0.8/lib/gpgme/ctx.rb:450:in `encrypt'
/usr/lib/ruby/gems/2.2.0/gems/gpgme-2.0.8/lib/gpgme/crypto.rb:99:in `block in encrypt'
/usr/lib/ruby/gems/2.2.0/gems/gpgme-2.0.8/lib/gpgme/ctx.rb:71:in `new'
/usr/lib/ruby/gems/2.2.0/gems/gpgme-2.0.8/lib/gpgme/crypto.rb:90:in `encrypt'
/home/lars/src/sup/lib/sup/crypto.rb:195:in `encrypt'
/home/lars/src/sup/lib/sup/util.rb:658:in `method_missing'
/home/lars/src/sup/lib/sup/modes/edit_message_mode.rb:586:in `build_message'
/home/lars/src/sup/lib/sup/modes/edit_message_mode.rb:525:in `send_message'
/home/lars/src/sup/lib/sup/mode.rb:59:in `handle_input'
/home/lars/src/sup/lib/sup/buffer.rb:222:in `handle_input'
./bin/sup:270:in `<module:Redwood>'
./bin/sup:74:in `<main>'

**Comment by gauteh** [comment]
Is this still an issue?

**Comment by gauteh** [comment]
need info
