### ISSUE TITLE
rmail being maintained again

### ISSUE THREAD

**Issue by terceiro** [sup-heliotrope/sup#394]
I got in touch with the gem owners for rmail and permission to push new versions. I have added a bunch of patches that got accumulated in the Debian package for supporting newer Ruby versions, plus fixed to the test suite etc, and I am willing to maintain it going forward.

There is a 1.1.0 release uploaded to rubygems with those fixes, and I am now looking at the issues and pull requests from your `sup-rmail` fork. It would be nice if you could use that instead of a local fork.

See [terceiro/rmail](https://github.com/terceiro/rmail)

**Comment by gauteh** [comment]
Great! We should definitely move over to your fork and drop sup-rmail
from rubygems. Do you have all our changes (or equivalent) incorporated
already?

**Comment by eMBee** [comment]
this is interesting. given that the switchover to mail has not made much progress, it would be interesting to know what were/are the issues with rmail, and then to evaluate if fixing them is easier than completing the switch-over to mail.

**Comment by terceiro** [comment]
> Great! We should definitely move over to your fork and drop sup-rmail
> from rubygems. Do you have all our changes (or equivalent) incorporated
> already?

yes, as far as I can tell.

**Comment by gauteh** [comment]
On your repository you don't allow for opening issues, and also the web page you refer to leads nowhere.

**Comment by terceiro** [comment]
ah sorry I didn't notice that I had to explicitly enable issues. Did that just now.

re homepage  I guess you meant the one in the repo description, that was just copied from the original repo I guess, I deleted that.

**Comment by gauteh** [comment]
Hi, there has been an open PR on your repository since july (not judging, lots of open here too). I am just wondering whether you are still maintaining your fork, otherwise it is not much point in switching from rmail-sup.

**Comment by terceiro** [comment]
I am maintaining it. Merging changes to the README is not exactly high on my TODO list though.

**Comment by gauteh** [comment]
Ok, just switched over to your fork. Seems like all rmail related tests pass on our side.
