### ISSUE TITLE
else without rescue is useless

### ISSUE THREAD

**Issue by wrigleyster** [sup-heliotrope/sup#399]
I keep getting errors like this:
```
$GEMHOME/gems/sup-0.21.0/lib/sup/modes/thread_index_mode.rb:1030: warning: else without rescue is useless
```
I'm using  ruby-2.2 and sup-0.21.0 on arch linux

**Comment by cscorley** [comment]
Hi @gauteh, 

Simple line change fixes this. Feel free to pull the change in or modify it using your preferred construct.

**Comment by gauteh** [comment]
Thanks for the PR, wasn't quite what I was trying to do initially (your code would catch too many errors), so I replaced it with just a typed out version of if..else.

**Comment by cscorley** [comment]
Indeed. Thanks!
