### ISSUE TITLE
Updated gems. Sup now crashes with an error about "undefined method 'yaml_tag'

### ISSUE THREAD

**Issue by Wartz** [sup-heliotrope/sup#403]
/home/joe/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup.rb:30:in `yaml_properties': undefined method `yaml_tag' for Redwood::MBox:Class (NoMethodError)
	from /home/joe/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup/mbox.rb:10:in `<class:MBox>'
	from /home/joe/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup/mbox.rb:6:in `<module:Redwood>'
	from /home/joe/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup/mbox.rb:4:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/joe/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup.rb:423:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/joe/.gem/ruby/2.2.0/gems/sup-0.21.0/bin/sup:21:in `<top (required)>'
	from /home/joe/.gem/ruby/2.2.0/bin/sup:23:in `load'
	from /home/joe/.gem/ruby/2.2.0/bin/sup:23:in `<main>

I'm guessing this is something to do with a new ruby version and yaml/psych, but I can't be much more helpful than that unless someone else knows what to look for.

**Comment by rakoo** [comment]
Weird... `yaml_tag` is part of `psych` which is part of ruby's stdlib since 1.9.3, and it should be loaded at that moment...

Out of curiosity (don't know if it's going to help a lot), could you please run these ?

```shell
$ ruby --version
$ ruby -e 'require "psych"; puts Object::yaml_tag "blah"'
```

**Comment by Wartz** [comment]
joe@Joe-Arch-20150109 ~ % ruby --version                                                           :(
    ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]


    joe@Joe-Arch-20150109 ~ % ruby -e 'require "psych"; puts Object::yaml_tag "blah"'
    blah

As a side note, renaming my entire .gem folder and re-downloading sup with all its dependencies (making sure to download xapian-ruby first before sup) fixed it.

I'm copying over each gem folder one at a time to see if I can isolate the problem any further.

**Comment by maxmeyer** [comment]
Is it possible that you installed "psych" via rubygems? I had similar problems and removing the gem fixed this for me.

**Comment by Wartz** [comment]
Excerpts from maxmeyer's message of 2015-03-12 00:16:22 -0700:
> Is it possible that you installed "psych" via rubygems? I had similar problems and removing the gem fixed this for me.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sup-heliotrope/sup/issues/403#issuecomment-78433867

Thanks, this worked perfectly!

I'm still curious though why installing psych would break sup, since
psych is included in ruby by default, right?

-- 
Joe Schlimmer

**Comment by gauteh** [comment]
Excerpts from Joe Schlimmer's message of March 12, 2015 10:02:
> Excerpts from maxmeyer's message of 2015-03-12 00:16:22 -0700:
>> Is it possible that you installed "psych" via rubygems? I had similar problems and removing the gem fixed this for me.
>> 
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/sup-heliotrope/sup/issues/403#issuecomment-78433867
> 
> Thanks, this worked perfectly!
> 
> I'm still curious though why installing psych would break sup, since
> psych is included in ruby by default, right?

It probably just breaks psych, which sup depends on.

**Comment by maxmeyer** [comment]
@gauteh 

Why not close this issue?  :smile:

**Comment by gauteh** [comment]
Closed :)
