### ISSUE TITLE
Sup dies if maildir is synchronized with file copying

### ISSUE THREAD

**Issue by rapha8l** [sup-heliotrope/sup#404]
Hi,
My title may be not very clear. 
In fact, I have a maildir I uses with another client, and the maildir for sup which is syncrhonized by rsync with the first one every minute.
Sup seems not to like that messages may disappear or appear not by this way and crashes all the time  : 

--- RuntimeError from thread: load threads for thread-index-mode

/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:615:in `find_docid'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:620:in `find_doc'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:630:in `get_entry'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:236:in `block in build_message'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:639:in `synchronize'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:236:in `build_message'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:230:in `block (2 levels) in each_message_in_thread_for'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/thread.rb:355:in `call'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/thread.rb:355:in `block in load_thread_for_message'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:230:in `block in each_message_in_thread_for'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:230:in `each'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:230:in `each_message_in_thread_for'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/thread.rb:353:in `load_thread_for_message'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/thread.rb:345:in `block in load_n_threads'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:165:in `block in each_id_by_date'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:288:in `block in each_id'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:288:in `each'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:288:in `each_id'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:165:in `each_id_by_date'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/thread.rb:340:in `load_n_threads'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/modes/thread_index_mode.rb:686:in `load_n_threads'
(eval):12:in `load_n_threads'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/modes/thread_index_mode.rb:670:in `block in load_n_threads_background'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup.rb:88:in `block in reporting_thread'
--- RuntimeError from thread: periodic poll

/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:615:in `find_docid'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:620:in `find_doc'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:803:in `block in index_message_threading'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:803:in `map'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:803:in `index_message_threading'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:717:in `sync_message'
(eval):1:in `sync_message'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:215:in `block in poll_from'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/maildir.rb:161:in `block in poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/maildir.rb:160:in `each'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/maildir.rb:160:in `each_with_index'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/maildir.rb:160:in `poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:201:in `poll_from'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:146:in `block (2 levels) in do_poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:136:in `each'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:136:in `block in do_poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:135:in `synchronize'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:135:in `do_poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/util.rb:658:in `method_missing'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/modes/poll_mode.rb:15:in `poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:58:in `poll_with_sources'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:94:in `poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:119:in `block in start'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup.rb:88:in `block in reporting_thread'

Also :

--- RuntimeError from thread: poll after loading inbox

/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:615:in `find_docid'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:620:in `find_doc'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:181:in `message_joining_killed?'
(eval):1:in `message_joining_killed?'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:217:in `block in poll_from'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/maildir.rb:161:in `block in poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/maildir.rb:160:in `each'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/maildir.rb:160:in `each_with_index'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/maildir.rb:160:in `poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:201:in `poll_from'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:146:in `block (2 levels) in do_poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:136:in `each'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:136:in `block in do_poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:135:in `synchronize'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:135:in `do_poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/util.rb:658:in `method_missing'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/modes/poll_mode.rb:15:in `poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:58:in `poll_with_sources'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:94:in `poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/util.rb:658:in `method_missing'
/var/lib/gems/2.1.0/gems/sup-999/bin/sup:208:in `block (2 levels) in <module:Redwood>'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup.rb:88:in `block in reporting_thread'

Thanks

Raphael

**Comment by ZJvandeWeg** [comment]
Why would you sync with rsync is a continues process? I suspect you've already read [this?](https://github.com/sup-heliotrope/sup/wiki/Using-sup-with-other-clients)

**Comment by rapha8l** [comment]
Thanks, I did not knew this, I've just tried without great luck :

[2015-03-16 12:38:53 +0100] ERROR: oh crap, an exception
----------------------------------------------------------------
We are very sorry. It seems that an error occurred in Sup. Please
accept our sincere apologies. Please submit the contents of
/home/rsalle/.sup/exception-log.txt and a brief report of the
circumstances to https://github.com/sup-heliotrope/sup/issues so that
we might address this problem. Thank you!

Sincerely,
The Sup Developers
----------------------------------------------------------------
--- RuntimeError from thread: load threads for thread-index-mode

/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:615:in `find_docid'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:620:in `find_doc'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:630:in `get_entry'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:236:in `block in build_message'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:639:in `synchronize'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:236:in `build_message'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:230:in `block (2 levels) in each_message_in_thread_for'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/thread.rb:355:in `call'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/thread.rb:355:in `block in load_thread_for_message'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:230:in `block in each_message_in_thread_for'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:230:in `each'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:230:in `each_message_in_thread_for'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/thread.rb:353:in `load_thread_for_message'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/thread.rb:345:in `block in load_n_threads'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:165:in `block in each_id_by_date'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:288:in `block in each_id'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:288:in `each'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:288:in `each_id'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:165:in `each_id_by_date'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/thread.rb:340:in `load_n_threads'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/modes/thread_index_mode.rb:686:in `load_n_threads'
(eval):12:in `load_n_threads'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/modes/thread_index_mode.rb:670:in `block in load_n_threads_background'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup.rb:88:in `block in reporting_thread'
--- RuntimeError from thread: periodic poll

/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:615:in `find_docid'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:620:in `find_doc'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:803:in `block in index_message_threading'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:803:in `map'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:803:in `index_message_threading'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:717:in `sync_message'
(eval):1:in `sync_message'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:215:in `block in poll_from'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/maildir.rb:161:in `block in poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/maildir.rb:160:in `each'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/maildir.rb:160:in `each_with_index'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/maildir.rb:160:in `poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:201:in `poll_from'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:146:in `block (2 levels) in do_poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:136:in `each'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:136:in `block in do_poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:135:in `synchronize'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:135:in `do_poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/util.rb:658:in `method_missing'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/modes/poll_mode.rb:15:in `poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:58:in `poll_with_sources'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:94:in `poll'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/poll.rb:119:in `block in start'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup.rb:88:in `block in reporting_thread'

**Comment by ZJvandeWeg** [comment]
Is this the master branch? As the version of sup seems to be sup-999. If so, when have you last pulled master? 
Also, please set an envoirement variable, SUP_LOG_LEVEL to debug.

But as you already pointed out; sup doesn't like it when you move the files youself. Why would you rsync this and not use something like OfflineImap?

**Comment by rapha8l** [comment]
Hi,
I've pulled the master two days ago.
This time, I've installed sup with "gem install sup"
I've used it on a classic maildir with offlineimap and no synchronization nor rsync.
First sup-sync-back-maildir crashes on maildir with 540 messages with :

/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:615:in `find_docid': unhandled exception
        from /var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:620:in `find_doc'
        from /var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:630:in `get_entry'
        from /var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:236:in `block in build_message'
        from /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
        from /var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:639:in `synchronize'
        from /var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:236:in `build_message'
        from /var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:301:in `block in each_message'
        from /var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:288:in `block in each_id'
        from /var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:288:in `each'
        from /var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:288:in `each_id'
        from /var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:300:in `each_message'
        from /var/lib/gems/2.1.0/gems/sup-999/bin/sup-sync-back-maildir:102:in `block (2 levels) in <top (required)>'
        from /var/lib/gems/2.1.0/gems/sup-999/bin/sup-sync-back-maildir:100:in `each'
        from /var/lib/gems/2.1.0/gems/sup-999/bin/sup-sync-back-maildir:100:in `block in <top (required)>'
        from /var/lib/gems/2.1.0/gems/sup-999/bin/sup-sync-back-maildir:92:in `each'
        from /var/lib/gems/2.1.0/gems/sup-999/bin/sup-sync-back-maildir:92:in `<top (required)>'
        from /usr/local/bin/sup-sync-back-maildir:23:in `load'
        from /usr/local/bin/sup-sync-back-maildir:23:in `<main>'

Then launching sup, it loads and then crash :

--- RuntimeError from thread: load threads for thread-index-mode

/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:615:in `find_docid'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:620:in `find_doc'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:630:in `get_entry'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:236:in `block in build_message'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:639:in `synchronize'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:236:in `build_message'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:230:in `block (2 levels) in each_message_in_thread_for'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/thread.rb:355:in `call'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/thread.rb:355:in `block in load_thread_for_message'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:230:in `block in each_message_in_thread_for'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:230:in `each'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:230:in `each_message_in_thread_for'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/thread.rb:353:in `load_thread_for_message'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/thread.rb:345:in `block in load_n_threads'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:165:in `block in each_id_by_date'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:288:in `block in each_id'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:288:in `each'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:288:in `each_id'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/index.rb:165:in `each_id_by_date'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/thread.rb:340:in `load_n_threads'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/modes/thread_index_mode.rb:686:in `load_n_threads'
(eval):12:in `load_n_threads'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup/modes/thread_index_mode.rb:670:in `block in load_n_threads_background'
/var/lib/gems/2.1.0/gems/sup-999/lib/sup.rb:88:in `block in reporting_thread'


Thanks for helping

**Comment by ZJvandeWeg** [comment]
If you are certain you've got your sources well configured; could you please backup your index.
Than 
```bash
$ cd ~/.sup
$ sup-dump > sup-backup-<insert-date-here>.bak
$ export SUP_LOG_LEVEL="debug"
$ rm -r xapian
$ sup
```
Now I suspect you're fine again, as the index had files which might not exist because off the rsync on the folder. The initial building might take a while. If you are in a hurry, quit sup and `$ sup-sync`.

If sup *hangs* or so, please don't quit just yet. Press ; to see all buffers, and go to the log buffer and post that here please.

**Comment by gauteh** [comment]
Excerpts from ZJvandeWeg's message of March 17, 2015 14:16:
> If you are certain you've got your sources well configured; could you
> please backup your index. Than ```bash $ cd ~/.sup $ sup-dump >
> sup-backup-<insert-date-here>.bak $ export SUP_LOG_LEVEL="debug" $ rm
> -r xapian $ sup ``` Now I suspect you're fine again, as the index had
> files which might not exist because off the rsync on the folder. The
> initial building might take a while. If you are in a hurry, quit sup
> and `$ sup-sync`.
> 
> If sup *hangs* or so, please don't quit just yet. Press ; to see all
> buffers, and go to the log buffer and post that here please.

Note that you can find the log in .sup/log as well.

- gaute

**Comment by rapha8l** [comment]
ZJvandeWeg :
Thanks again, deleting xapian seems to resolve most of the problems.
Before, I didn't even had to quit sup, it crashed all on itself
