### ISSUE TITLE
Installation errors under ubuntu

### ISSUE THREAD

**Issue by twodayslate** [sup-heliotrope/sup#408]
Below is the output. I tried getting support on IRC but that didn't seem to be very active. 

https://ghostbin.com/paste/nuapd

https://ghostbin.com/paste/vdq4p

**Comment by ZJvandeWeg** [comment]
Support for Ruby 1.9 and below has been dropped. But the ubuntu repo's cant be this far behind, are they?

**Comment by ZJvandeWeg** [comment]
It seems Ubuntu's mirrors are lagging a bit on ruby versions. (http://packages.ubuntu.com/trusty/ruby) You might want to install rvm first and use 2.X.

**Comment by twodayslate** [comment]
That appears to have been part of the problem. The [wiki](https://github.com/sup-heliotrope/sup/wiki/Installation%3A-Debian-and-Ubuntu) references 1.9 FYI. I was missing a lot of dependencies. 

Here are the errors I am getting now: https://ghostbin.com/paste/w2z3b

Thanks for the help!

**Comment by ZJvandeWeg** [comment]
Is your ~/.sup folder empty? Especially no config.yaml? If so, could you paste it here?

Btw, if you just want to get going, you could run `sup`, quit it, there should be a valid `config.yaml` now in your sup folder.

**Comment by twodayslate** [comment]
The `~/.sup/` folder is not empty and the configuration file exists. 

https://ghostbin.com/paste/9rr8q

**Comment by ZJvandeWeg** [comment]
`rm config.yaml` -- The config file layout is not what it is supposed to be, therefor sup has no clue what your current config is and crashes.
Now `sup-config` or `sup` *should* run again.

**Comment by twodayslate** [comment]
Seems to be working now. Thanks for the support!
