### ISSUE TITLE
`yaml_properties': undefined method `yaml_tag' 

### ISSUE THREAD

**Issue by masterkorp** [sup-heliotrope/sup#409]
After importing my maildir with ``sup-config`` I get this:
```ruby
$ sup
/home/myuser/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup.rb:30:in `yaml_properties': undefined method `yaml_tag' for Redwood::MBox:Class (NoMethodError)
	from /home/masterkorp/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup/mbox.rb:10:in `<class:MBox>'
	from /home/masterkorp/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup/mbox.rb:6:in `<module:Redwood>'
	from /home/masterkorp/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup/mbox.rb:4:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/myuser/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup.rb:423:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /home/myuser/.gem/ruby/2.2.0/gems/sup-0.21.0/bin/sup:21:in `<top (required)>'
	from /home/myuser/.gem/ruby/2.2.0/bin/sup:23:in `load'
	from /home/myuser/.gem/ruby/2.2.0/bin/sup:23:in `<main>'
````

``sup --version`` also crashes so:
```
$ gem list sup 

*** LOCAL GEMS ***

rmail-sup (1.0.1)
sup (0.21.0)
```

Regards,
Alfredo Palhares

**Comment by ZJvandeWeg** [comment]
Seems familiar to #403 
Could you try that fix?

**Comment by masterkorp** [comment]
Hello @ZJvandeWeg 

``gem uninstall psych`` did the job thanks!

Should this be added to wiki, as it seems that is problem a problem that will happen to more users.

**Comment by gauteh** [comment]
Excerpts from Alfredo Palhares's message of March 27, 2015 12:43:
> Hello @ZJvandeWeg 
> 
> ``gem uninstall psych`` did the job thanks!
> 
> Should this be added to wiki, as it seems that is problem a problem that will happen to more users.

Yup!

**Comment by masterkorp** [comment]
This just happened again today after a ``gem update``

**Comment by lamarpavel** [comment]
Can confirm, this should either be well documented or sup should be able to deal with this properly (at least by giving a hint in the error message as to what the user can do).
Because breakage caused by an update, leaving the user with a stack-trace of ruby, is kind of the worst case scenario here.
