### ISSUE TITLE
else without rescue and deprecation

### ISSUE THREAD

**Issue by twodayslate** [sup-heliotrope/sup#411]
zac@shell:~$ sup-sync-back-maildir
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/modes/thread_index_mode.rb:1030: warning: else without rescue is useless
    Are you sure you want to synchronize 'maildir:/home/zac/personal/archive'? (Y/n) Y
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/bin/sup-sync-back-maildir:98: warning: Enumerator.new without a block is deprecated; use Object#to_enum
    [2015-03-31 09:59:09 -0400] Flushing Xapian updates to disk. This may take a while... 

Also

      zac@shell:~$ sup
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/modes/thread_index_mode.rb:1030: warning: else without rescue is useless
    Error: the index is locked by another process! User 'zac' on
    host 'shell' is running /home/zac/.rvm/gems/ruby-2.2.0/bin/sup with pid 27916.
    The process was alive as of at least 6 seconds ago.
    Should I ask that process to kill itself (y/n)? n
    Sorry, couldn't unlock the index.
    zac@shell:~$ jobs
    zac@shell:~$ sup
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/modes/thread_index_mode.rb:1030: warning: else without rescue is useless
    Error: the index is locked by another process! User 'zac' on
    host 'shell' is running /home/zac/.rvm/gems/ruby-2.2.0/bin/sup with pid 27916.
    The process was alive as of at least 0 seconds ago.
    Should I ask that process to kill itself (y/n)? y
    Let's try that again.
    I couldn't lock the index. The lockfile might just be stale.
    Should I just remove it and continue? (y/n) y
    Let's try that one more time.
    [2015-03-31 14:34:05 -0400] ERROR: oh crap, an exception
    ----------------------------------------------------------------
    We are very sorry. It seems that an error occurred in Sup. Please
    accept our sincere apologies. Please submit the contents of
    /home/zac/.sup/exception-log.txt and a brief report of the
    circumstances to https://github.com/sup-heliotrope/sup/issues so that                                                                                                                         
    we might address this problem. Thank you!
    Sincerely,
    The Sup Developers
    ----------------------------------------------------------------
    --- IOError from thread: main
    DatabaseLockError: Unable to get write lock on /home/zac/.sup/xapian: already locked
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/index.rb:120:in `initialize'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/index.rb:120:in `new'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/index.rb:120:in `load_index'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/index.rb:103:in `load'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/util.rb:658:in `method_missing'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/bin/sup:145:in `<module:Redwood>'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/bin/sup:75:in `<top (required)>'
    /home/zac/.rvm/gems/ruby-2.2.0/bin/sup:23:in `load'
    /home/zac/.rvm/gems/ruby-2.2.0/bin/sup:23:in `<main>'
    /home/zac/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
    /home/zac/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>' 

which then lead to 

    zac@shell:~$ sup
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/modes/thread_index_mode.rb:1030: warning: else without rescue is useless
    [2015-03-31 14:36:42 -0400] ERROR: oh crap, an exception
    ----------------------------------------------------------------
    We are very sorry. It seems that an error occurred in Sup. Please
    accept our sincere apologies. Please submit the contents of
    /home/zac/.sup/exception-log.txt and a brief report of the
    circumstances to https://github.com/sup-heliotrope/sup/issues so that                                                                                                                         
    we might address this problem. Thank you!
    Sincerely,
    The Sup Developers
    ----------------------------------------------------------------
    --- Encoding::CompatibilityError from thread: poll after loading inbox
    incompatible encoding regexp match (ASCII-8BIT regexp with UTF-8 string)
    /home/zac/.rvm/gems/ruby-2.2.0/gems/rmail-sup-1.0.1/lib/rmail/header.rb:81:in `=~'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/rmail-sup-1.0.1/lib/rmail/header.rb:81:in `parse'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/rmail-sup-1.0.1/lib/rmail/parser.rb:233:in `block in parse_header'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/rmail-sup-1.0.1/lib/rmail/parser.rb:229:in `each'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/rmail-sup-1.0.1/lib/rmail/parser.rb:229:in `parse_header'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/rmail-sup-1.0.1/lib/rmail/parser.rb:194:in `parse_low'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/rmail-sup-1.0.1/lib/rmail/parser.rb:183:in `parse'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/rmail-sup-1.0.1/lib/rmail/parser.rb:331:in `parse'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/rmail-sup-1.0.1/lib/rmail/parser.rb:345:in `read'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/message.rb:495:in `message_to_chunks'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/message.rb:476:in `block in message_to_chunks'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/message.rb:476:in `map'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/message.rb:476:in `message_to_chunks'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/message.rb:265:in `load_from_source!'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/message.rb:376:in `build_from_source'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:204:in `block in poll_from'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/maildir.rb:161:in `block in poll'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/maildir.rb:160:in `each'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/maildir.rb:160:in `each_with_index'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/maildir.rb:160:in `poll'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:201:in `poll_from'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:146:in `block (2 levels) in do_poll'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:136:in `each'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:136:in `block in do_poll'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:135:in `synchronize'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:135:in `do_poll'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/util.rb:658:in `method_missing'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/modes/poll_mode.rb:15:in `poll'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:58:in `poll_with_sources'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/poll.rb:94:in `poll'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup/util.rb:658:in `method_missing'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/bin/sup:208:in `block (2 levels) in <module:Redwood>'
    /home/zac/.rvm/gems/ruby-2.2.0/gems/sup-0.21.0/lib/sup.rb:88:in `block in reporting_thread'

**Comment by ZJvandeWeg** [comment]
In your first dump, these are just warnings and these don't break anything. Also, AFAIK, these are allready fixed in `develop`.
In the second; you can't run two instances of sup. As one was still running, and the killing just failed, the DB is still locked. It seems you've then; by trying to force sup to open, corrupted some mail messages in your maildir.

All these are warnings and error seems expected behavior.

**Comment by twodayslate** [comment]
I'm not on the `develop` branch so that would explain that. 

However, if my maildir is corrupted, should the expected behavior really be a crash? Wouldn't it be better to warn the user and handle the crash more gracefully?

**Comment by ZJvandeWeg** [comment]
Usually errors do not result in a crash and sup resumes operation if possible.
In this case however its the rmail-sup gem which crashes. On second look im really interested on which message. Could you find out?

**Comment by twodayslate** [comment]
After running sup, the program launches and I can switch between buffers etc;

After about 10 seconds of offlineimap running, the program crashes. I don't attempt to open any emails. 

https://ghostbin.com/paste/wc7ex

I have over 7k emails retrieved from offlineimap and not all have been synced with sup yet. This might be part of the problem? 

Let me know if you want me to run any specific commands to help with bug testing.

**Comment by rakoo** [comment]
Good ol' [encoding](https://github.com/sup-heliotrope/sup/issues?utf8=%E2%9C%93&q=label%3Aencoding+) issue. Is it possible for you to pinpoint the exact email where it happened, so we can reproduce and include it in some unit test ? If I remember correctly this command should output all the information you need in the console:

```shell
$ SUP_LOG_LEVEL=debug sup
```

Basically sup constantly polls your maildir for new/changed/deleted emails, and tries to import them. It doesn't matter that offlineimap is running in the backgroud or not (thanks to the design of maildirs), and it doesn't matter that sup doesn't have all the messages yet (they will eventually all be processed). There is however this specific message that breaks the flow.

**Comment by twodayslate** [comment]
Here is the output. https://ghostbin.com/paste/vfjhq

Any suggestions on how to find the email that is causing the crash?
