### ISSUE TITLE
Sometimes drafts do not appear on the inbox

### ISSUE THREAD

**Issue by masterkorp** [sup-heliotrope/sup#414]
Hello everyone,

Sometimes the draft emails I have saved do not appear on my inbox. To make them reappear I need to start a new email, and save as draft (by pressing P on edit mode) and the new draft and older drafts appear (this does not work everytime).

Also the draft tends to disappear when I update a new draft. 
I do this a lot because I do write lengthy emails.

I am using sup v0.21.0 from the gems

--
Regards,
Alfredo Palhares

**Comment by gauteh** [comment]
Is this the same as #230?

**Comment by masterkorp** [comment]
@gauteh Yes this seems to be exactly the same behaviour.

**Comment by gauteh** [comment]
Ok, then I'll close this issue as a duplicate, if you have any more
information or figure out a fix please use the first report.
