### ISSUE TITLE
Content-type headers that has spaces around equal-sign in charset parameter is not handled

### ISSUE THREAD

**Issue by yzzyx** [sup-heliotrope/sup#418]
I've recieved a couple of messages that have Content-type-headers looking like this:
   
    Content-Type: text/plain; charset = "utf-8"

as opposed to:

     Content-Type: text/plain; charset="utf-8"

The current matching rule won't work, and the contents will not get decoded properly.

**Comment by yzzyx** [comment]
added pull-request #419

**Comment by gauteh** [comment]
Fixed in #419.
