### ISSUE TITLE
DatabaseCorruptError: Expected block 30368 to be level 0, not 1

### ISSUE THREAD

**Issue by nanooq** [sup-heliotrope/sup#423]
After polling sup aborts with the following message:

--- IOError from thread: poll after loading inbox
DatabaseCorruptError: Expected block 30368 to be level 0, not 1
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/index.rb:338:in `_dangerous_allterms_begin'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/index.rb:338:in `each_prefixed_term'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/index.rb:351:in `each_source_info'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/maildir.rb:130:in `each'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/maildir.rb:130:in `to_a'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/maildir.rb:130:in `block (2 levels) in poll'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/util.rb:261:in `call'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/util.rb:261:in `block in benchmark'
/home/lora/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/util.rb:261:in `benchmark'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/maildir.rb:130:in `block in poll'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/maildir.rb:122:in `each'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/maildir.rb:122:in `poll'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/poll.rb:201:in `poll_from'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/poll.rb:146:in `block (2 levels) in do_poll'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/poll.rb:136:in `each'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/poll.rb:136:in `block in do_poll'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/poll.rb:135:in `synchronize'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/poll.rb:135:in `do_poll'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/util.rb:658:in `method_missing'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/modes/poll_mode.rb:15:in `poll'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/poll.rb:58:in `poll_with_sources'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/poll.rb:94:in `poll'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/util.rb:658:in `method_missing'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/bin/sup:222:in `block (2 levels) in <module:Redwood>'
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup.rb:88:in `block in reporting_thread'

**Comment by gauteh** [comment]
Oh, that looks bad, you got a backup?

Excerpts from Nanooq's message of April 23, 2015 13:40:
> After polling sup aborts with the following message:
> 
> 
> --- IOError from thread: poll after loading inbox
> DatabaseCorruptError: Expected block 30368 to be level 0, not 1
> /home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.20.0/lib/sup/index.rb:338:in `_dangerous_allterms_begin'

**Comment by nanooq** [comment]
A backup of what exactly? Mails are on also left on IMAP server and .sup folder is backuped every first of month. 

So, what further steps do you suggest? 

```
:~$ sup --version
/home/lora/.rvm/gems/ruby-2.1.5/gems/sup-0.21.0/lib/sup/modes/thread_index_mode.rb:1030: warning: else without rescue is useless
sup v0.21.0
```

**Comment by gauteh** [comment]
A backup of the index. There are some info on it in the tutorial. It
looks like the xapian index has been corrupted for some reason, perhaps
a crash during a write or something?

Excerpts from Nanooq's message of April 23, 2015 15:28:

**Comment by gauteh** [comment]
Maybe a newer version of xapian works better?

**Comment by nanooq** [comment]
Thank you, @gauteh. I used the backup from the 1st of April. I also updated all the gems including xapian. On my notebook, I was running sup in the background, when it ran out of energy last afternoon. Maybe the power outage was a bad timing. 
I therefore close this issue.

**Comment by gauteh** [comment]
Yep, that would be my bet. If you backup and compress the index it does
not take much time (or space) to keep a few of the last ones.

Excerpts from Nanooq's message of April 23, 2015 16:45:

**Comment by nanooq** [comment]
Elsewise I could delete .sup/xapian and run ```sup-sync``` see #372 - which takes longer than restoring the index.
