### ISSUE TITLE
RFC2047-encoded headers with spaces look bad

### ISSUE THREAD

**Issue by yzzyx** [sup-heliotrope/sup#424]
NOTE!
RFC2047 specifically says that it's forbidden to include spaces in encoded headers,
but there seems to be all too many broken MUA's out there.

Example:
Subject: =?ISO-8859-1?Q?PUNKDISTRO mailorder news 24.04.2015 / PISSE LP pr?=
    =?ISO-8859-1?Q?e-order?=

In this example, the first part will not get decoded, only the second part, because of the included spaces. Other mua's (i.e. thunderbird) gracefully handle this and assumes (correctly) that the spaces should have been encoded.

(There's also a second issue here, with multi-line subjects, that means that this will be displayed as
=?ISO-8859-1?Q?PUNKDISTRO mailorder news 24.04.2015 / PISSE LP pr?= e-order - with a space between the two parts, when there should have been no space, but that's another issue)

So - should I create a pull request for this? It's annoying, so I'll at least patch my own fork, but I think others would benefit from it as well, even though it doesn't follow the RFC.

**Comment by gauteh** [comment]
I think this could be included, anyway, it would be great with
test-cases that illustrate and test the problem.

I'd preferably like to have this in RMail, do you know if the Mail gem
handles this case correctly?

Excerpts from Elias Norberg's message of April 24, 2015 18:09:

**Comment by yzzyx** [comment]
RMail doesn't seem to have any RFC2047-code (which I guess is the reason there's a rfc2047.rb in sup). The "mail"-gem handles it correctly (tested with version 2.6.3).

I'll write a test-case and patch and make a pull request.

**Comment by gauteh** [comment]
Ok, thanks

**Comment by yzzyx** [comment]
Is the 'use-mail'-branch going to be merged (any time soon)?
Because it works fine there (since 'mail' is taking care of it).
I'll still patch the develop-tree, and add a test-case for regressions, but that's good news anyhow.

**Comment by gauteh** [comment]
It needs work, but @ZJvandeWeg is working on it (e.g. #426), check out #127 for status.

**Comment by gauteh** [comment]
ref #427.
