### ISSUE TITLE
Use the latest mime-types (2.5, just released)

### ISSUE THREAD

**Issue by halostatue** [sup-heliotrope/sup#425]
There have been a lot of [mime-types](https://github.com/mime-types/ruby-mime-types) added since 1.25.1, and there will be no updates at all to 1.x after October 27th, 2015. I also expect to release 3.0 later this year (absolutely no later than November 15th).

Because sup requires Ruby 2.0 or higher, you have no incompatibilities, and the `mail` gem is already using mime-types 2.x (and I expect to release another version soon that will enable lazy loading to reduce the memory usage by default).

**Comment by gauteh** [comment]
Duplicate in #182.

Has the API changed? Note that we are still using RMail (although there is a stale branch which changes sup over to the mail gem)

**Comment by halostatue** [comment]
I can check against RMail (which may be your larger limiting factor), but 2.x does not remove features from the API, except 1.8 support. It does mark a number of interfaces as deprecated that will be removed for 3.x.

**Comment by gauteh** [comment]
Ok, thanks. There is some effort in #127 to get changed over to mail.

**Comment by halostatue** [comment]
I have scanned both rmail (no mime-types dependency) and sup. You should be able to switch your dependency to '~> 2.0' with no problems whatsoever, and when 3.0 comes out, the interfaces you are using should still be good. The only thing you need to be aware of (for the 3.x line) is that I am going to be working on some behind-the-scene changes that will make certain lookups more reliably return registered types.

**Comment by gauteh** [comment]
Fixed.
