### ISSUE TITLE
Gem build partially broken in mkrf_conf_xapian

### ISSUE THREAD

**Issue by Karunamon** [sup-heliotrope/sup#429]
Greetings,

4a59310f7d0360413b9643d5fc61d79edcabb716 which removed all `require 'rubygems'*` lines appears to have broken the ability to build sup as a gem, as [ext/mkrf_conf_xapian.rb](https://github.com/sup-heliotrope/sup/blob/4a59310f7d0360413b9643d5fc61d79edcabb716/ext/mkrf_conf_xapian.rb) calls out to other Rubygems specific functions.

```
#  gem specific_install https://github.com/sup-heliotrope/sup.git develop -V
Building native extensions.  This could take a while...
/Users/mparks/.rbenv/versions/2.1.2/bin/ruby mkrf_conf_xapian.rb
mkrf_conf_xapian.rb:4:in `<main>': uninitialized constant Gem::Command (NameError)
ERROR:  While executing gem ... (Gem::Ext::BuildError)
    ERROR: Failed to build gem native extension.
Building has failed. See above output for more information on the failure.
rake failed, exit code 1
```

**Comment by ZJvandeWeg** [comment]
Thanks for pointing me towards `specific_install`!
I have just reproduced this, will look into this as rubygems should be autoloaded already.

**Comment by gauteh** [comment]
@ZJvandeWeg: should I revert 4a59310 or do you want to look into this?

**Comment by ZJvandeWeg** [comment]
I was thinking, only revert the change for the specific file. 
Do you agree?

Gaute Hope <notifications@github.com> schreef op 22 mei 2015 09:49:35 CEST:
>@ZJvandeWeg: should I revert 4a59310 or do you want to look into this?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sup-heliotrope/sup/issues/429#issuecomment-104554732

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gauteh** [comment]
That should be good. Could you make a PR? (then we can get it tested as
well).

Excerpts from ZJvandeWeg's message of May 22, 2015 10:28:
> I was thinking, only revert the change for the specific file. 
> Do you agree?

**Comment by gauteh** [comment]
@Karunamon can you test #431?

**Comment by rapha8l** [comment]
Hi,

I still get :
gem install sup                                                                         
Building native extensions.  This could take a while...
ERROR:  Error installing sup:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 mkrf_conf_xapian.rb
mkrf_conf_xapian.rb:5:in `<main>': uninitialized constant Gem::Command (NameError)

rake failed, exit code 1


thanks

**Comment by gauteh** [comment]
The whole mkrf_xapian thing is needed because we need a special dependency on freebsd, if there is another way of doing that now we could just skip the whole thing.

**Comment by rapha8l** [comment]
newbie question (I don't code) : is there a way to specify an "if" case based on os type ?

**Comment by gauteh** [comment]
It did not use to be a way to do that for the gem file (in the gemspec).

**Comment by gauteh** [comment]
original fix from #327

**Comment by gauteh** [comment]
Can you test #439 ?

**Comment by rapha8l** [comment]
Sorry to ask, but how can I test ?
Thanks

**Comment by gauteh** [comment]
I just merged and pushed a new release, could you test if sup-0.22.1
works?

- gaute

Excerpts from rapha8l's message of June 17, 2015 15:07:

**Comment by Karunamon** [comment]
You should be able to grab the specific install addon for Gem, point it at this repo, and if successful, it'll work without failing as described in the first message.

I'll try this today as well.

**Comment by Karunamon** [comment]
Build successful, looks good. Thanks!

**Comment by rapha8l** [comment]
It works
Thanks a lot

**Comment by ZJvandeWeg** [comment]
@gauteh 
Sorry for not responding to this bug. Was kind of busy.

**Comment by gauteh** [comment]
@ZJvandeWeg: no worries. thanks for all the other stuff you did!

**Comment by cubranic** [comment]
sup-0.22.1 still fails for me on FreeBSD 10.1:

> /usr/home/davor/.rbenv/versions/2.0.0-p645/bin/ruby mkrf_conf_xapian.rb
> xapian: platform specific dependencies..
> xapian: installing xapian-ruby..
> Building native extensions.  This could take a while...
> ERROR:  Error installing sup:
>	ERROR: Failed to build gem native extension.
>
>    Building has failed. See above output for more information on the failure.
>
> Gem files will remain installed in /usr/home/davor/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/sup-0.22.1 for inspection.
> Results logged to /usr/home/davor/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/sup-0.22.1/ext/gem_make.out

I see no information on what actually caused the error either on the screen or in 'gem_make.out' even though I ran `gem install` with the verbose flag.

**Comment by cubranic** [comment]
I'm guessing my problem might be in xapian-ruby:

```
/bin/sh ../libtool  --tag=CXX    --mode=link c++ -fno-strict-aliasing -Wall -Wno-unused -Wno-uninitialized -fvisibility=hidden -I/usr/home/davor/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/xapian-ruby-1.2.20/xapian-core-1.2.20/include  -g -O2 -avoid-version -module -shrext ".so"  -L/usr/home/davor/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/xapian-ruby-1.2.20/lib -o _xapian.la -rpath /usr/home/davor/.rbenv/versions/2.0.0-p645/lib/ruby/site_ruby/2.0.0/x86_64-freebsd10.1 xapian_wrap.lo /usr/home/davor/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/xapian-ruby-1.2.20/xapian-core-1.2.20/libxapian.la -lstdc++  
libtool: link: c++  -fPIC -DPIC -shared -nostdlib /usr/lib/crti.o /usr/lib/crtbeginS.o  .libs/xapian_wrap.o   -Wl,-rpath -Wl,/usr/home/davor/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/xapian-ruby-1.2.20/xapian-core-1.2.20/.libs -Wl,-rpath -Wl,/usr/home/davor/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/xapian-ruby-1.2.20/lib -L/usr/home/davor/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/xapian-ruby-1.2.20/lib /usr/home/davor/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/xapian-ruby-1.2.20/xapian-core-1.2.20/.libs/libxapian.so -lz -lstdc++ -L/usr/lib -lc++ -lm -lc -lgcc -lgcc_s /usr/lib/crtendS.o /usr/lib/crtn.o  -O2   -Wl,-soname -Wl,_xapian.so -o .libs/_xapian.so
/usr/bin/ld: cannot find -lstdc++
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by gauteh** [comment]
Yeah, this looks like an xapian-ruby issue. You could try to install it
manually and see if you get more output.

**Comment by cubranic** [comment]
Tracking xapian-ruby error at garaio/xapian-ruby#3.
