### ISSUE TITLE
Sync back labels

### ISSUE THREAD

**Issue by masterkorp** [sup-heliotrope/sup#432]
Hello,

For me the missing feature of making my own email service as good as the other hosted solutions (eg Gmail) is labels sync back to the Maildir.

- What is really missing to achieve this?
- If someone would like to propose a patch for this, where should it start ?
- How do you recommend writing tests for this feature ?

**Comment by maxmeyer** [comment]
I think this is not supported by Maildir. Maybe http://wiki2.dovecot.org/MailboxFormat/Maildir is helpful for implementing this.

**Comment by gauteh** [comment]
Check out the maildir-root branch + wiki as well as the gmail syncback
pull-request.

Excerpts from Max Meyer's message of May 26, 2015 20:35:

**Comment by gauteh** [comment]
#253

and: https://github.com/sup-heliotrope/sup/tree/maildir-root

**Comment by gauteh** [comment]
#322
