### ISSUE TITLE
Purge mails

### ISSUE THREAD

**Issue by maxmeyer** [sup-heliotrope/sup#437]
Hi there,

is it possible to purge mails from Maildir? I really want to delete mails and not only mark them as delete?

**Comment by gauteh** [comment]
Excerpts from Max Meyer's message of May 30, 2015 10:31:
> Hi there,
> 
> is it possible to purge mails from Maildir? I really want to delete
> mails and not only mark them as delete?
> 

There are some suggested scripts for that, check other issues, mailing
list archives and wiki. I do not know how well they work though.

- gaute

**Comment by gauteh** [comment]
This can be done with hooks, or a addon script.

**Comment by maxmeyer** [comment]
Ok. Thanks.

**Comment by gauteh** [comment]
#175.

**Comment by maxmeyer** [comment]
Thanks a lot.
