### ISSUE TITLE
Delete an attachment in the thread-view-mode  

### ISSUE THREAD

**Issue by kantntreiber** [sup-heliotrope/sup#438]
It would be nice being able to delete an attachment in the thread-view-mode and not rely on a MUA like mutt to do that.

**Comment by gauteh** [comment]
Do you mean to delete it from a received message, to save disk space?

Excerpts from kantntreiber's message of June 4, 2015 8:41:

**Comment by kantntreiber** [comment]
Thanks for the quick reply.

Yes, that is what I meant. The typical use case is that one receives an email, saves the attachment, so it does not longer make sense to keep a copy of the attachment in the mailbox.

**Comment by gauteh** [comment]
Sup does not really change the mailbox so I do not think this will be
implemented, it would require the message to be re-written. It could
probably be achieved with a hook and a keybinding extension. There are
some issues/posts on the mailinglist where adding new keybindings have
been demonstrated.

Excerpts from kantntreiber's message of June 4, 2015 14:47:
