### ISSUE TITLE
Lockfile:StolenLockError when attempting to remove a stale lockfile.

### ISSUE THREAD

**Issue by Wartz** [sup-heliotrope/sup#440]
joe@Joe-Arch-20150109 ~ % sup 
    /home/joe/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup/modes/thread_index_mode.rb:1030: warning:       else without rescue is useless
      Error: the index is locked by another process! User 'joe' on
      host 'Joe-Arch-20150109' is running /home/joe/.gem/ruby/2.2.0/bin/sup with pid 8698.
      The process was alive as of at least 2 seconds ago.
 
    Should I ask that process to kill itself (y/n)? y
    Let's try that again.
    I couldn't lock the index. The lockfile might just be stale.
    Should I just remove it and continue? (y/n) y
    Let's try that one more time.
    [2015-06-17 09:26:29 -0400] ERROR: oh crap, an exception
    ----------------------------------------------------------------
    We are very sorry. It seems that an error occurred in Sup. Please
    accept our sincere apologies. Please submit the contents of
    /home/joe/.sup/exception-log.txt and a brief report of the
    circumstances to https://github.com/sup-heliotrope/sup/issues so that
    we might address this problem. Thank you!
 
    Sincerely,
    The Sup Developers
    ----------------------------------------------------------------
    --- IOError from thread: main
    DatabaseLockError: Unable to get write lock on /home/joe/.sup/xapian: already locked
    /home/joe/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup/index.rb:120:in `initialize'
    /home/joe/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup/index.rb:120:in `new'
    /home/joe/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup/index.rb:120:in `load_index'
    /home/joe/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup/index.rb:103:in `load'
    /home/joe/.gem/ruby/2.2.0/gems/sup-0.21.0/lib/sup/util.rb:658:in `method_missing'
    /home/joe/.gem/ruby/2.2.0/gems/sup-0.21.0/bin/sup:145:in `<module:Redwood>'
    /home/joe/.gem/ruby/2.2.0/gems/sup-0.21.0/bin/sup:75:in `<top (required)>'
    /home/joe/.gem/ruby/2.2.0/bin/sup:23:in `load'
    /home/joe/.gem/ruby/2.2.0/bin/sup:23:in `<main>'

This is reproducible with the following steps.

i3-wm on arch.
Start sup in a Urxvt terminal.
Force close the terminal with $mod+shift+q
Open a new terminal.
Start up sup again.

**Comment by gauteh** [comment]
are you sure the old sup process is gone? you can remove the lock file manually as well.

**Comment by gauteh** [comment]
I don't think this is a bug, the old sup process is still running, probably doing a poll or something that takes a little while.

**Comment by gauteh** [comment]
Closing as not-a-bug.
