### ISSUE TITLE
Add option to select server for sending email

### ISSUE THREAD

**Issue by binaryplease** [sup-heliotrope/sup#447]
Hello,

I need the option to select the server when sending email.
At the moment msmtp uses the default account, it would be nice to be able to switch select the correct one when sending, the default should be the account the email was send to.

Is there such an option or a workaround?

My msmtprc looks like this:

````
defaults
auth on
tls on
tls_trust_file /etc/ssl/certs/ca-certificates.crt

account personal
host smtp.gmail.com
user user@gmail.com
from user@gmail.com 
password 
port 587

account work
host smtp.hostname.de
user user@server2.com
password 
port 587

account default : personal

````

**Comment by gauteh** [comment]
You can either have msmtp guess your account: https://github.com/sup-heliotrope/sup/wiki/Complete-gmail-configuration#Configuring-msmtp or you can specify the account on the command line for the per-account sendmail config option in .sup/config
