### ISSUE TITLE
Document how to integrate and use contacts

### ISSUE THREAD

**Issue by binaryplease** [sup-heliotrope/sup#448]
As a new user I'm struggeling to understand how to use contacts in sup.
I would like to be able to use my google contacts and to know how to select them when composing a new mail.

**Comment by aliceriot** [comment]
Hey Pablo,

I wrote a small python program a while back to get your google contacts into
sup. Check it out here:

https://github.com/aliceriot/supContacts.py

-- 
~*~ alice ~*~
PGP fingerprint: 43D1 4BEF 39F7 4027 B02A DC4D 3D47 670F 4226 9A83

**Comment by binaryplease** [comment]
Thanks, but that doesn't seem to work anymore.
```
8 June 2015: GoogleCL is currently broken due to the OAuth1 turndown, and likely to remain so. Thanks for your support over the years, and apologies for the lack of prior notice.
```
Is there another option?

**Comment by aliceriot** [comment]
Well, that's no good! Sorry for the non-help!

**Comment by binaryplease** [comment]
I came up with a way to at least get the google contacts into sup.
I use this scipt i wrote:

https://gist.github.com/binaryplease/b0e3ce3c33fb642b7a23

With it you can use the export functionality from gmail and convert the downloaded document to a format that sup will understand. This solution is far from perfect though since you have to repeat the process of download and convert everytime your gmail contacts have changed

**Comment by binaryplease** [comment]
Sorry for the double post, but I just discovered goobook an utitly to query google contacts via command line. This could be a solution to this.

https://gitlab.com/goobook/goobook

**Comment by gauteh** [comment]
These might also be interesting, lbdb plugins for sup and goobook:

https://gist.github.com/gauteh/6111461
https://gist.github.com/gauteh/4704061

Pablo Ovelleiro Corral writes on August 18, 2015 7:37:

**Comment by rakoo** [comment]
Just like in #462, I guess the best way to do it is to write a few  `extra-contact-addresses` hooks in the wiki, with `goobook` here, `abook` in #462, ...

**Comment by rakoo** [comment]
I just created [this page](https://github.com/sup-heliotrope/sup/wiki/External-contacts-search), feel free to add other external hooks as needed.

**Comment by gauteh** [comment]
@rakoo: what do you think about #463? this should get entries from extra-contact-lists into the contact list.

**Comment by rakoo** [comment]
@gauteh yeah, that's a neat idea. #463 doesn't work as is though, I modified it a little bit
