### ISSUE TITLE
Document interaction with /var/mail/$USERNAME

### ISSUE THREAD

**Issue by sgtatham** [sup-heliotrope/sup#451]
I've just been looking into switching to Sup from my old MUA. There's some specific documentation on the wiki of how to work with various kinds of remote mail source (IMAP, gmail), but oddly, I don't see anything about how to use Sup with a traditional local Unix mbox-shaped mail spool in a file such as `/var/mail/simon`.

The obvious command is `sup-add mbox:/var/mail/simon`; but if I understand correctly, doing so would cause all messages to be indexed as living in `/var/mail/simon` and never moved out of there. But that's not a viable long-term storage policy: my email may _arrive_ in `/var/mail`, but I need it to ultimately end up somewhere in my home directory, because `/var` is on a different partition with less free space and a different backup policy. I would imagine that surely _most_ people using a `/var/mail` spool file have the same requirement; it's generally not considered sensible to leave your entire mail archive in `/var/mail` forever.

It seems to me that what I'd most like is for Sup to automatically move new messages out of `/var/mail/simon` into a file in my home directory, and then index them in that location. But I can't see anything along these lines in the `sup-add` help, or anywhere else. So, have I missed it somewhere? Or is there some other way that Sup can support this mail delivery arrangement? What do existing users in this sort of situation do?

(Or am I the last person in the universe still using email in this old-fashioned way? :-)

Whatever the answer turns out to be, it seems to me that this could usefully be added to the wiki.

**Comment by rakoo** [comment]
Hello,

Yeah, sup was designed to never touch the emails once they've been imported. The best thing you can do is have another program that takes all mails from `/var/mail/simon` and writes them to an inbox in your `$HOME`, and instructs sup to read _that_ file. Unfortunately a quick google search didn't find a lot of answers there, only interesting result is `convert-and-create` from [here](http://www.qmailwiki.org/index.php/Qmail-maildir).

Now, AFAIU (I'm too young to have known spool files :-), the point of spool files is that it can act as a buffering zone between the MDA and the MUA: the MDA can write as many mails as it wants, and the MUA quietly reads them one by one, and they don't step on each other's toes. Correct ? In this case you might want to use maildirs that provide this same guarantee (writers and readers not blocking each other) and is fully managed by sup.

**Comment by sgtatham** [comment]
But I'm not the sysadmin of the machine where I read my mail, so I can't switch the system MDA over to using maildirs.

Actually, looking further through the docs, I now realise that perhaps the `before-poll.rb` hook is what I want. I can designate some folder in my home dir (mbox _or_ maildir, my choice) as the source from Sup's point of view, but have a `before-poll` hook which moves new messages into there from `/var/mail/simon`.

If I come up with something that looks nicely reusable, I'll suggest it for the wiki.

**Comment by rakoo** [comment]
True, the `before-poll.rb` hook is most likely what you want; if you can come up with something that solves your problem I'm sure it will be interesting not just for sup users but for everyone with similar situations :)

**Comment by gauteh** [comment]
Let us know if you solved this, closing for now as this is not a defect in sup.
