### ISSUE TITLE
Archive in Gmail

### ISSUE THREAD

**Issue by binaryplease** [sup-heliotrope/sup#455]
Hello,

when using sup with a Gmail account, pressing "a" archives the message inside sup, but it is still visible via the gmail.com webpage. Also It still is unread and not archived. The same for the mail client on my phone.

Deleting "d" the message, removes them from gmail and other clients. The message stays in gmails archive (which is what i wanted) but is no longer searchable inside sup.

What is the correct configuration/usage when dealing with Gmail + Archive feature?

Thanks.

**Comment by gauteh** [comment]
Sup does not change gmail labels or move messages between maildirs. There are branches and efforts to do both, but none of them have seen any action in a while and are probably outdated. The reason delete works is that it is a maildir-flag, these are synced. Check out maildir-root or one of the gmail-sync options if you wish to test these branches. You would need to update them with the latest code from develop though.
