### ISSUE TITLE
Crash when changing To: in reply mode

### ISSUE THREAD

**Issue by guiniol** [sup-heliotrope/sup#458]
Whenever I reply and want to change the To: field using the shortcut 't', sup crashes. Editing the header directly when editing the message works.
Here is the log file:

```
--- NoMethodError from thread: main
undefined method `join' for "cidre <cidre@sympa.rennes.supelec.fr>":String
/home/guiniol/.gem/ruby/2.2.0/gems/sup-0.22.1/lib/sup/modes/edit_message_mode.rb:648:in `edit_field'
/home/guiniol/.gem/ruby/2.2.0/gems/sup-0.22.1/lib/sup/modes/reply_mode.rb:212:in `edit_field'
/home/guiniol/.gem/ruby/2.2.0/gems/sup-0.22.1/lib/sup/modes/edit_message_mode.rb:202:in `edit_to'
/home/guiniol/.gem/ruby/2.2.0/gems/sup-0.22.1/lib/sup/mode.rb:59:in `handle_input'
/home/guiniol/.gem/ruby/2.2.0/gems/sup-0.22.1/lib/sup/buffer.rb:222:in `handle_input'
/home/guiniol/.gem/ruby/2.2.0/gems/sup-0.22.1/bin/sup:255:in `<module:Redwood>'
/home/guiniol/.gem/ruby/2.2.0/gems/sup-0.22.1/bin/sup:74:in `<top (required)>'
/home/guiniol/.gem/ruby/2.2.0/bin/sup:23:in `load'
/home/guiniol/.gem/ruby/2.2.0/bin/sup:23:in `<main>'
```

Tell me what more information I can give.

**Comment by danc86** [comment]
I can't reproduce this, using the develop branch or the 0.22.1 tag.

`header["To"]` is expected to be an array, and as far as I can see it always will be. But the stack trace indicates `header["To"]` was somehow a string instead. The only way I can think this might happen is if the `before-edit` hook modified `header["To"]` to be a string.

**Comment by danc86** [comment]
Please re-open if you have more information about how to reproduce this.
