### ISSUE TITLE
Add support for abook

### ISSUE THREAD

**Issue by binaryplease** [sup-heliotrope/sup#462]
Hello,
Abook (http://abook.sourceforge.net/) is used a lot with text based mail clients.
It would be nice if it could be integrated with mutt since it provides some benifits e.g

- It provides a nicer console based ui to query, edit and retrieve contacts.
- It can export to a lot of formats
- It can import a lot of formats
- It can find and remove duplicates
- It can be used from within a mail client as well as standalone to view contacts
- It supports other contact fields like phone number, address etc.
- A lot of other functions

I think it shouldn't be very difficult to integrate since it is designed to be integrated in mutt.
It can be queried from the console like this:

```
 abook --mutt-query	<string>
````

which returns a list of matching contacts, also they can be added like this

```
abook 	--add-email	
```
 It reads an e-mail message from stdin and add the sender to the addressbook.

I think the profits would be great, no point in inventing the wheel twice.
Thanks,
Pablo

**Comment by gauteh** [comment]
Hi,

You should be able to do this with the extra-contact-addresses hook. Not
sure if you can do it per query, but if you can list all contacts from
abook then you should get them included.


Pablo Ovelleiro Corral writes on August 17, 2015 21:54:

**Comment by binaryplease** [comment]
You can list all contacts with 
```
abook --mutt-query '' 
````

That is two single quotes at the end. The empty string matches everything.
But, that only works for tab completion, not for listing the contacts with 'C'.
Is there a way to show them in contact-list-mode?

By the way: I don't understand how I select one of the entries when tab completion has multiple results. Is it possible to cycle throught the results in a zsh-like way (arrow keys or tab) or do i have to keep typing until there is only one result?

**Comment by binaryplease** [comment]
My code for trying  this is 

``` ruby


  out = []
`abook --mutt-query ''`.each_line do |l| 
  line = ''
  l.chomp.split.each do |w|
    line << w.chomp
    line << ' '
  end
  out << line.strip unless line.strip.empty?
end
out

```
But I can't see any contacts from abook. Am I doing this wrong? I can confirm the code words on its one when executed and returns a array of strings with contacts.

**Comment by gauteh** [comment]
have you put this code in SUP_BASE/hooks/extra-contact-addresses.rb ?

you will probably only get these while completing, not sure if they show
up in the contact list.

perhaps try ```return out``` at the end.

**Comment by gauteh** [comment]
Can you test if #463 shows the contacts in the list as well, note that hooks and stuff have been moved to .local/sup in newest develop.

**Comment by gauteh** [comment]
by the way, your script would be a good candidate for the wiki if you
have the chance to add it there:

  https://github.com/sup-heliotrope/sup/wiki/Hooks

**Comment by binaryplease** [comment]
> Can you test if #463 shows the contacts in the list as well, note that hooks and stuff have been 
> moved to .local/sup in newest develop.

Sorry but I dont really know how to do that, if you can elaborate, I'd be glad to help.
I'm using Archlinux and installed sup via rvm on ruby-2.2.2. My sup -v is sup v0.22.1.

**Comment by gauteh** [comment]
Pablo Ovelleiro Corral writes on August 18, 2015 17:35:
>> Can you test if #463 shows the contacts in the list as well, note that hooks and stuff have been 
>> moved to .local/sup in newest develop.
> 
> Sorry but I dont really know how to do that, if you can elaborate, I'd be glad to help.
> I'm using Archlinux and installed sup via rvm on ruby-2.2.2. My sup -v is sup v0.22.1.

have a look at: https://github.com/sup-heliotrope/sup/wiki/Running-from-git

To test the branch, add my repository and check it out:

```
$ git remote add gauteh https://github.com/gauteh/sup.git
$ git fetch gauteh
$ git checkout -b c-list-extra gauteh/c-list-extra
```
