### ISSUE TITLE
Crash --- TypeError from thread: load threads for thread-index-mode

### ISSUE THREAD

**Issue by binaryplease** [sup-heliotrope/sup#464]
I'm running sup from git.
I followed the instructions from here:
https://github.com/sup-heliotrope/sup/wiki/Running-from-git

When started I get an empty sup with the line at the bottom:
"Searching for threads..."

If I press any key, sup crashes, this is the trace:

```
binaryplease➜~/Projects/sup(master)» bin/sup                                                                                                                                                                                        [20:58:32]
[2015-08-19 20:59:55 +0200] ERROR: oh crap, an exception
----------------------------------------------------------------
We are very sorry. It seems that an error occurred in Sup. Please
accept our sincere apologies. Please submit the contents of
/home/binaryplease/.local/share/sup/exception-log.txt and a brief report of the
circumstances to https://github.com/sup-heliotrope/sup/issues so that
we might address this problem. Thank you!

Sincerely,
The Sup Developers
----------------------------------------------------------------
--- TypeError from thread: load threads for thread-index-mode
no implicit conversion from nil to integer
/home/binaryplease/Projects/sup/lib/sup/buffer.rb:719:in `[]='
/home/binaryplease/Projects/sup/lib/sup/buffer.rb:719:in `block in clear'
/home/binaryplease/Projects/sup/lib/sup/buffer.rb:718:in `synchronize'
/home/binaryplease/Projects/sup/lib/sup/buffer.rb:718:in `clear'
/home/binaryplease/Projects/sup/lib/sup/util.rb:614:in `method_missing'
/home/binaryplease/Projects/sup/lib/sup/modes/thread_index_mode.rb:699:in `load_n_threads'
(eval):12:in `load_n_threads'
/home/binaryplease/Projects/sup/lib/sup/modes/thread_index_mode.rb:670:in `block in load_n_threads_background'
/home/binaryplease/Projects/sup/lib/sup.rb:103:in `block in reporting_thread'
--- TypeError from thread: checking for idleness
no implicit conversion from nil to integer
/home/binaryplease/Projects/sup/lib/sup/buffer.rb:719:in `[]='
/home/binaryplease/Projects/sup/lib/sup/buffer.rb:719:in `block in clear'
/home/binaryplease/Projects/sup/lib/sup/buffer.rb:718:in `synchronize'
/home/binaryplease/Projects/sup/lib/sup/buffer.rb:718:in `clear'
(eval):1:in `clear'
/home/binaryplease/Projects/sup/lib/sup/modes/thread_index_mode.rb:505:in `flush_index'
/home/binaryplease/Projects/sup/lib/sup/modes/inbox_mode.rb:77:in `handle_idle_update'
/home/binaryplease/Projects/sup/lib/sup/update.rb:26:in `block in relay'
/home/binaryplease/Projects/sup/lib/sup/update.rb:26:in `each'
/home/binaryplease/Projects/sup/lib/sup/update.rb:26:in `relay'
/home/binaryplease/Projects/sup/lib/sup/util.rb:614:in `method_missing'
/home/binaryplease/Projects/sup/lib/sup/idle.rb:29:in `block in start'
/home/binaryplease/Projects/sup/lib/sup.rb:103:in `block in reporting_thread'
```

**Comment by thisismiller** [comment]
I had success doing the following to resolve this crash and have a usable sup.

    --- ~/workspace/sup/lib/sup/modes/thread_index_mode.rb	2015-08-19 15:14:14.223000597 -0700
    +++ ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/modes/thread_index_mode.rb	2015-08-19 16:21:39.849627540 -0700
    @@ -696,7 +696,7 @@
         @ts.threads.each { |th| th.labels.each { |l| LabelManager << l } }
     
         update
    -    BufferManager.clear @mbid
    +    BufferManager.clear @mbid if @mbid
         @mbid = nil
         BufferManager.draw_screen
         @ts.size - orig_size

No idea if this is safe or correct though.

**Comment by gauteh** [comment]
this is related to the same issue as the getlocal error. sup is trying to update the display (as a result of the key press) while the display has not yet been updated to the search result being loaded.

**Comment by gauteh** [comment]
Alex Miller writes on August 20, 2015 1:25:
> I had success doing the following to resolve this crash and have a usable sup.
> 
>     --- ~/workspace/sup/lib/sup/modes/thread_index_mode.rb	2015-08-19 15:14:14.223000597 -0700
>     +++ ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/modes/thread_index_mode.rb	2015-08-19 16:21:39.849627540 -0700
>     @@ -696,7 +696,7 @@
>          @ts.threads.each { |th| th.labels.each { |l| LabelManager << l } }
>      
>          update
>     -    BufferManager.clear @mbid
>     +    BufferManager.clear @mbid if @mbid
>          @mbid = nil
>          BufferManager.draw_screen
>          @ts.size - orig_size
> 
> No idea if this is safe or correct though.

We have a bunch of these quick-fixes already, if you make a PR I can
merge it. Fixing the whole issue requires some serious synchronization.

**Comment by nanooq** [comment]
fix worked for me, thanks
