### ISSUE TITLE
Use regex in alternates

### ISSUE THREAD

**Issue by regnat** [sup-heliotrope/sup#465]
I got many different email addresses redirecting to my main address (in particular addresses in the form my.account_tag@domain.com which are redirected to my.account@domain.com).
It would be nice to be able to use regex do determine alternates addresses (so that we should set something like my.account_.*@domain.com or my.account@(domain1.com|domain2.net) ).

**Comment by gauteh** [comment]
Is this for purposes of replying or tagging on message arrival?

**Comment by regnat** [comment]
It's for purpose of replying only, I don't need it for tagging (and it should anyway be done as tagging is managed by a ruby hook).

Excerpts from Gaute Hope's message of 2015-08-22 15:17:27 +0800:

**Comment by gauteh** [comment]
Then it is possible to use the before-edit hook to choose account.

Théophane Hufschmitt writes on August 25, 2015 4:30:

**Comment by gauteh** [comment]
Gaute Hope writes on August 25, 2015 8:36:
> Then it is possible to use the before-edit hook to choose account.

use something like:

```

if header['To'] =~ /account/
  header['From'] = 'A B <my.account@domain.com>'
end

```

**Comment by regnat** [comment]
Thanks for the tip, I didn't think it would be possible via hooks.

If someone is interested, the "reply-from" hook does exactly what I wanted.

Excerpts from Gaute Hope's message of 2015-08-25 19:42:44 +0800:

**Comment by gauteh** [comment]
If it is something that could be used by others, please consider adding it to the wiki under the hooks section.
