### ISSUE TITLE
Check for internet connection

### ISSUE THREAD

**Issue by binaryplease** [sup-heliotrope/sup#466]
When sup is started without internet connection or the internet connection went away and it runs offlineimap this is displayed:

![nointernetbug](https://cloud.githubusercontent.com/assets/1719781/9413917/35eeac98-4835-11e5-84e8-7727561f4236.png)

This could be avoided by checking for interent connectin before running offlineimap or catching the error and would make offline reading of emails better.

**Comment by rakoo** [comment]
sup doesn't really care about internet connectivity: it uses an external program to "send" emails, and polls the filesystem to "receive" mails. I believe you run offlineimap in the `before-poll` hook. It should be the external program's duty to check for connectivity (if ever it needs it), but we could provide some easy ruby code to check for connectivity in a hook then.

**Comment by lamarpavel** [comment]
>but we could provide some easy ruby code to check for connectivity in a hook then.

Or sup handle the output of offlineimap more gracefully, eg. by parsing the error message and printing something apropriate to the status line at the bottom.

**Comment by gauteh** [comment]
you can catch those errors by capturing stdout and stderr from
offlineimap when polling, then you can also create your own status line
depending on the output and exit code.

sup does not know about offlineimap or any program fetching mail, it
just checks for new messages in the maildir. the before-poll hook does
that stuff (depending on what the user has it do) and could use other
programs than offlineimap. it is therefore not so good to make
offlineimap-specific code.

you can check for internet connection in the before-poll hook with
something like:

```
online = system ('ping -W 1 -c 1 mail.google.com') # replace with your mail server
```

then optionally run offlineimap.

duplicate: #381.

**Comment by gauteh** [comment]
Closing, this can be done in a hook. #381 can be kept open in case we want to make a conditional poll.
