### ISSUE TITLE
Signing messages appear to be broken on newer GPG

### ISSUE THREAD

**Issue by HiTECNOLOGYs** [sup-heliotrope/sup#468]
I'm not sure whether this is GPGME's fault or just sup doing it wrong but I couldn't make it sign my messages while encryption working fine. I'm no Ruby programmer and even though I can read and write simple snippets of code due to familiarity with Python, I don't know how to extract needed information.

The only error I get is:
```
Problem sending mail: Exception in GPGME call: General error
```

I have also tried the following example to verify GPGME operation:
```ruby
#!/usr/bin/env ruby
require 'gpgme'

crypto = GPGME::Crypto.new
signature = crypto.clearsign('This is a test message!')

puts signature.read
```
and I got the following error:
```
/usr/lib64/ruby/gems/2.2.0/gems/gpgme-2.0.10/lib/gpgme/ctx.rb:475:in `sign': General error (GPGME::Error::General)
	from /usr/lib64/ruby/gems/2.2.0/gems/gpgme-2.0.10/lib/gpgme/crypto.rb:249:in `block in sign'
	from /usr/lib64/ruby/gems/2.2.0/gems/gpgme-2.0.10/lib/gpgme/ctx.rb:79:in `new'
	from /usr/lib64/ruby/gems/2.2.0/gems/gpgme-2.0.10/lib/gpgme/crypto.rb:242:in `sign'
	from /usr/lib64/ruby/gems/2.2.0/gems/gpgme-2.0.10/lib/gpgme/crypto.rb:331:in `clearsign'
	from test.rb:5:in `<main>'
```
which does not look very good.

I've tried both versions from gem utility and my ports (I'm using Gentoo) which are both 2.0.10 but none provided expected output.

I've tried using various keys and subkeys but without success as well.

The GPG version is 2.1.7-r1.
The system GPGME version is 1.5.5.
The Ruby GPGME bindings version is 2.0.10.
The sup version is 0.22.1.

Assistance would be really appreciated.
Thanks!

**Comment by BlacklightShining** [comment]
This seems unrelated to Sup, given that you're getting that error even when Sup isn't involved at all.

**Comment by HiTECNOLOGYs** [comment]
@BlacklightShining seems to me too, was just making sure I've not mistakenly analysed the facts. Maybe the errors look the same but they aren't? Is the code I used even correct? You think this is GPGME's fault and I should move this to its tracker? Sorry for being silly but this all the really terra incognita for me.

**Comment by HiTECNOLOGYs** [comment]
Wait, I'm an idiot. Sleep deprivation is a bad thing. The problem was that I accidentally forgot to move secret subkey to the computer I used to sign data with which caused GPG to be unable to sign anything. Sorry for bothering, everything is now working as it should. =P

**Comment by BlacklightShining** [comment]
@HiTECNOLOGYs Maybe reopen this on `gpgme`s tracker so they can make that raise|throw a more specific error.

**Comment by HiTECNOLOGYs** [comment]
@BlacklightShining sounds like a good idea. Will do.
