### ISSUE TITLE
TypeError from thread: checking for idleness / no implicit conversion from nil to integer

### ISSUE THREAD

**Issue by lsfxz** [sup-heliotrope/sup#473]
So even after the fix for #464 I get a seemingly somewhat related error whenever sup idles enough for the idly "Flushing index.." to happen.

The exception log is:

    --- TypeError from thread: checking for idleness
    no implicit conversion from nil to integer
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/buffer.rb:719:in `[]='
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/buffer.rb:719:in `block in clear'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/buffer.rb:718:in `synchronize'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/buffer.rb:718:in `clear'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/util.rb:614:in `method_missing'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/modes/thread_index_mode.rb:508:in `flush_index'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/modes/inbox_mode.rb:77:in `handle_idle_update'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/update.rb:26:in `block in relay'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/update.rb:26:in `each'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/update.rb:26:in `relay'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/util.rb:614:in `method_missing'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/idle.rb:29:in `block in start'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup.rb:103:in `block in reporting_thread'

This can be prevented by changing line 505 in thread_index_mode.rb to `BufferManager.clear @flush_id if @flush_id`.

With both these fixes in place at least sup doesn't crash, but things don't get redrawn properly:

![sup](https://cloud.githubusercontent.com/assets/13353732/9964394/4e801006-5e30-11e5-9c0e-3e69a686bea1.png)

Those issues did not occur with a version from git from July, if that helps.

Maybe related: Since switching to the newer sup using "say" in a hook doesn't work anymore (crashes somewhere in highline.say), too, while BufferManager.say works: 

    [2015-09-18 17:35:54 +0200] hook: error running /home/abcdef/.local/share/sup/hooks/before-poll.rb: wrong number of arguments (2 for 1)
    [2015-09-18 17:35:54 +0200] hook: /usr/lib/ruby/gems/2.2.0/gems/highline-1.7.3/lib/highline.rb:620:in `say'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/hook.rb:15:in `say'
    /home/abcdef/.local/share/sup/hooks/before-poll.rb:9:in `__run'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/hook.rb:65:in `eval'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/hook.rb:65:in `__run'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/hook.rb:98:in `run'
    (eval):1:in `run'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/poll.rb:53:in `poll_with_sources'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/poll.rb:94:in `poll'   
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup/util.rb:614:in `method_missing'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/bin/sup:249:in `block (2 levels) in <module:Redwood>'
    /usr/lib/ruby/gems/2.2.0/gems/sup-999/lib/sup.rb:103:in `block in reporting_thread' 
 

Unfortunately I still know very little ruby, so I'm out of ideas here.

/edit
Well, after some more errors and some more rummaging through the code all I can assume is that something is amiss with BufferManager.say and/or highline/highline.say. BufferManager.say doesn't seem to return an id as it should (?), highline crashes for different reasons. compose_mode crashes with "can't dup Symbol" in highline/question.rb when asking for a subject ( with BufferManager.ask).

/edit
After desperately trying to get some logging output from buffer.rb I managed to use NetBeans to remote-debug sup. Unfortunately I'm unable to debug BufferManager.say (or .clear): Neither logging in those functions works, nor am I able to make it break on breakpoints or able to step in the methods there. It feels like they're never run, but I must be missing something here.
(Breakpoints elsewhere seem to work, as does code for logging)

**Comment by lsfxz** [comment]
So... after even more tinkering and even considering switching to notmuch/alot.. I found it.
After trying a clean ruby environment, reinstalling gems, trying with older gems, ncurses and so on.. I followed the lead of being unable to debug BufferManager.say. Indeed, even when renaming .say did not change any behaviour at all I was certain it was actually never called when something used BufferManager.say. With this in mind and the few commits there were to be the culprit, it seems like requiring util/axe in bin/sup and axe subsequently requiring highline/import seems to be the problem: Although I do not understand why, it seems like this causes highlines say to be used (and maybe even ask, although I didn't check for it), which leads to many different kinds of crashes, either due to a missing returned id or whatever else when dup-ing in highlines question.rb.

So: just commenting out lines 10 and 56-58 (everything with axe) fixes _all_ my problems above, and probably #477, maybe even #476. Just commenting it out might not be the best solution (as it's not asking anymore on changing to XDG-paths), but it seems to be what's causing the problems.

**Comment by rakoo** [comment]
Thank you *very much* for your analysis. I had a look at `highline`, and indeed there's [this](https://github.com/JEG2/highline/blob/6d8677a6cb011b9bb322e9d97a6541064a027d26/lib/highline/import.rb#L15):

```ruby
module Kernel
  extend Forwardable
  def_delegators :$terminal, :agree, :ask, :choose, :say
end
```

So basically, `say` is redefined as `highline`'s one. Moreover even `BufferManager.say` is redirected to `highline`'s one.

**Comment by rakoo** [comment]
Hmmm, it's not like it's anything new... investigating.

**Comment by gauteh** [comment]
I suspect fa6ce11 could be the culprit *cough* *cough*.

Matthieu Rakotojaona writes on September 22, 2015 20:30:

**Comment by rakoo** [comment]
Okay, I think I got it: according to [this blog post](http://www.thirdbit.net/articles/2007/08/01/10-things-you-should-know-about-method_missing/) the order of method lookup is, in order:

1. search in this instance
1. search in instance-level methods for this class
1. search in included modules, from last to first
1. repeat in parent and parent's parent up until `Object`
1. search in Kernel
1. run `method_missing`

So, because `say` is defined in `Kernel` through `highline/import`, it doesn't run `method_missing` in [the Singleton module](https://github.com/sup-heliotrope/sup/blob/develop/lib/sup/util.rb#L597), so every `say` in `BufferManager` is broken.

(This may seem obvious for a rubybender, but this has always been a fuzzy part for me)

Here's a quick fix: since we know we're going to need it, force it in the definition of `BufferManager`:

```ruby
diff --git a/lib/sup/buffer.rb b/lib/sup/buffer.rb
index 603a1f8..3a356bd 100644
--- a/lib/sup/buffer.rb
+++ b/lib/sup/buffer.rb
@@ -680,6 +680,7 @@ EOS
     Ncurses.mutex.unlock unless opts[:sync] == false
   end
 
+  def self.say s, id=nil; @instance.say(s, id) end
   def say s, id=nil
     new_id = nil
 ```

It is quite possible that fa6ce11481d5f14aa43aed92ef90682bf92e5a94 could have introduced it by requiring `sup/util/axe` and thus `highline/import` and thus mucking around with Kernel.

**Comment by rakoo** [comment]
With `ask`:

```ruby
diff --git a/lib/sup/buffer.rb b/lib/sup/buffer.rb
index 603a1f8..80f0100 100644
--- a/lib/sup/buffer.rb
+++ b/lib/sup/buffer.rb
@@ -531,6 +531,7 @@ EOS
 
   ## for simplicitly, we always place the question at the very bottom of the
   ## screen
+  def self.ask domain, question, default=nil, &block; @instance.ask(domain, question, default, &block) end
   def ask domain, question, default=nil, &block
     raise "impossible!" if @asking
     raise "Question too long" if Ncurses.cols <= question.length
@@ -680,6 +681,7 @@ EOS
     Ncurses.mutex.unlock unless opts[:sync] == false
   end
 
+  def self.say s, id=nil; @instance.say(s, id) end
   def say s, id=nil
     new_id = nil
 
```

**Comment by abinoam** [comment]
Hi all,

You can avoid poluting the upper namespace by instantiating HighLine by yourself.



```ruby

# require 'highline/import' # REMOVE this line

# use this instead
require 'highline'

cli = HighLine.new
cli.ask "Ask as normal"
```

**Comment by abinoam** [comment]
I think the above will be the "recommended" way of using HighLine for the next versions.

cc: @JEG2

**Comment by gauteh** [comment]
@abinoam: thanks a lot!

@lsfxz: could you test #478?

**Comment by lsfxz** [comment]
Seems to work, no crashes anymore.

**Comment by abinoam** [comment]
You're welcome!
I'm really happy it helped you fix the bug @gauteh
