### ISSUE TITLE
WARNING: Problem sending mail: Exception in GPGME call: General error

### ISSUE THREAD

**Issue by nanooq** [sup-heliotrope/sup#475]
Hello all!

I am running sup v0.22.1 and today, I was looking into using GPG some more, especially at trouble-shooting. As I have not found a solution, please point me into the correct direction.

Sending an "encrypt only" e-mail, gpgme seems to abort. I cannot send the email, but am able to discard it or send it as unencrypted and unsigned. This is what the log file shows:

2015-09-20 12:23:02 +0200] Welcome to Sup! Log level is set to info.
[2015-09-20 12:23:02 +0200] For more verbose logging, restart with SUP_LOG_LEVEL=debug.
[2015-09-20 12:23:15 +0200] WARNING: Problem sending mail: Exception in GPGME call: General error

When sending an email encrypted and signed, I am being asked for my passphrase. Nevertheless, the correct passphrase is not accepted. After three attemps, sup informs me: 

Problem sending mail: Exception in GPGME call: Bad passphrase

I am then able to discard the email or send it as unsigned and unencrypted.

Signing is possible - it accepts the passphrase and send the email.

This behavior is quite nebulous to me. Assuming that signing works great but encrypting does not, I point the finger to the following bit of code: 

sup/lib/crypto.rb line 179:

crypto.encrypt(format_payload(payload), gpg_opts)

How can I further trace the problem?

**Comment by gauteh** [comment]
Hi nannoq,

please check #475 and #471: I think this issue came in with one of the
later gpgme versions. If you'd have the chance at narrowing it down to
which gpgme-version that this problem starts with we might be able to
use the changes of gpgme as a clue to where the problem is. At the
moment the problem might also be in gpgme.



Nanooq writes on September 20, 2015 12:33:

**Comment by schoeke** [comment]
@nanooq What OS are you using? Also, information about your gpg version might help narrowing it down. In #474, I am fighting a similar issue.

**Comment by nanooq** [comment]
Today I tried gpgme-2.0.10 to gpgme-2.0.7 to no avail.

gpg (GnuPG) 1.4.16
ruby 2.1.5p273 (2014-11-13 revision 48405) [i686-linux]
32-Bit Linux 3.13.0-57-generic #95-Ubuntu 

@schoeke: is "Sign only" working for you?

**Comment by schoeke** [comment]
Yes, signing works.
 gpg versions and ruby versions are different. What underlying version of gpgme are you using?

**Comment by nanooq** [comment]
I experience the same misbehaviour with 
gpgme-2.0.10 
gpgme-2.0.9
gpgme-2.0.8
gpgme-2.0.7
Have you already been poking in gpgme's source code?

**Comment by schoeke** [comment]
Well, the gpgme version you mention are the ruby gem. I was wondering about the underlying C lib. 

I have looked at it, but can't really make much out of it. I am not really a ruby person. I have the feeling, that there is not much else I can do here.

**Comment by nanooq** [comment]
I am now looking at 
https://github.com/ueno/ruby-gpgme/blob/master/lib/gpgme/crypto.rb#L76-77

@schoeke Have you trusted all your keys?

**Comment by schoeke** [comment]
Does not change anything.

**Comment by nanooq** [comment]
well, at least I am able to send encrypted emails to my other address. that was not possible before. Weirdly, I am asked for the recipients (my other email) key passphrase.

**Comment by schoeke** [comment]
That makes no sense. O_O

**Comment by nanooq** [comment]
@foobacca is the sender added to the list of recipients, so that it is assured that sender is able to read his own emails?
https://github.com/sup-heliotrope/sup/blame/develop/lib/sup/crypto.rb#L171

**Comment by schoeke** [comment]
Yes, that is standard. 

Could you try sending me an encrypted email and see if it still occurs? KeyID: D25E5E87

**Comment by nanooq** [comment]
I just sent you an encrypted message. I was not asked for a passphrase - which is to be expected. 
Then I tried sending you a signed encrypted message. I got the error: 
Problem sending mail: Exception in GPGME call: Bad passphrase (I checked my passphrase and it is correct).

**Comment by schoeke** [comment]
I received your message, but got an error:

Exception in GPGME call: Decryption failed

It did not even ask me for my password.

**Comment by gauteh** [comment]
Let us continue the discussion in #474.
