### ISSUE TITLE
libmenuw.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by masterkorp** [sup-heliotrope/sup#485]
Hello,

I recently updated my Arch System, and updated all my gems. While starting sup, I got this message:

```
$ sup 
/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require': libmenuw.so.5: cannot open shared object file: No such file or directory - /home/myuser/.gem/ruby/2.2.0/extensions/x86_64-linux/2.2.0/ncursesw-1.4.9/ncursesw_bin.so (LoadError)
  from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
  from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
  from /home/myuser/.gem/ruby/2.2.0/extensions/x86_64-linux/2.2.0/ncursesw-1.4.9/ncursesw.rb:23:in `<top (required)>'
  from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  from /home/myuser/.gem/ruby/2.2.0/gems/sup-0.22.1/bin/sup:6:in `<top (required)>'
  from /home/myuser/.gem/ruby/2.2.0/bin/sup:23:in `load'
  from /home/myuser/.gem/ruby/2.2.0/bin/sup:23:in `<main>'
```

The library just changed.
```
$ pacman -Ql | grep libmenu
lib32-ncurses /usr/lib32/libmenu.so
lib32-ncurses /usr/lib32/libmenuw.so
lib32-ncurses /usr/lib32/libmenuw.so.6
lib32-ncurses /usr/lib32/libmenuw.so.6.0
ncurses /usr/lib/libmenu.so
ncurses /usr/lib/libmenuw.so
ncurses /usr/lib/libmenuw.so.6
ncurses /usr/lib/libmenuw.so.6.0
```

Regards,
Alfredo Palhares

**Comment by gauteh** [comment]
you probably need to recompile ruby ncurses or install ncurses compat

Alfredo Palhares writes on September 28, 2015 15:50:

**Comment by masterkorp** [comment]
I did rebuild the gem with:
```
$ gem pristine ncursesw
Restoring gems to pristine condition...
Building native extensions.  This could take a while...
Restored ncursesw-1.4.9
```

Also did that to the sup gem, the problem still persists.

**Comment by timonv** [comment]
I had the same problem on arch today. Make sure you shell out first. I did a `gem pristine --all`, then had to reinstall sup, which worked.

**Comment by maxmeyer** [comment]
Same for me as well. Re-install of sup was neccessary.

**Comment by masterkorp** [comment]
Ok, after a few tries, I got it, to remove ``sup``  **and** to remove and reinstall the ``ncusrsesw`` gem. A ``gem pristine ncursesw`` (or a ``--all`` for that matter).

This seems to be a problem for [ncursesw](https://github.com/sup-heliotrope/ncursesw-ruby).

**Comment by masterkorp** [comment]
Opened an issue on the [proper place](https://github.com/sup-heliotrope/ncursesw-ruby/issues/31), @gauteh I think this issue can be closed.

**Comment by gauteh** [comment]
This could probably go in the troubleshooting section of the wiki.

**Comment by rakoo** [comment]
Created https://github.com/sup-heliotrope/sup/wiki/ncurses-dependency-update-from-5-to-6

**Comment by masterkorp** [comment]
@rakoo 
![everything-fine](https://cloud.githubusercontent.com/assets/223763/10281571/3bf70cc4-6b6d-11e5-8e6d-51479a5bda1c.gif)
