### ISSUE TITLE
Can't toggle unread label

### ISSUE THREAD

**Issue by tsroten** [sup-heliotrope/sup#487]
`unread` is one of sup's reserved labels. This makes sense in a lot of ways. However, from what I can tell it means that the `before-add-message.rb` hook can't mark a message as read. It also means that you can't remove the `unread` label from a selection of tagged messages.

Marking messages as unread via hooks and tags seems like a pretty common scenario. Is there another way to do this?

**Comment by tsroten** [comment]
Actually now that I look again, I think the `before-add-message.rb` hook is marking them as read. I still wonder about marking tagged messages as read, though.

**Comment by gauteh** [comment]
You can usually use 'N' to toggle the unread tag.

**Comment by tsroten** [comment]
Ah, yes! Thanks!

**Comment by hughwilliams94** [comment]
@gauteh How des one go about toggling 'N' in the before-add-message hook
