### ISSUE TITLE
Server returns "501 Syntax error - line too long" when sending html attachment

### ISSUE THREAD

**Issue by dset0x** [sup-heliotrope/sup#489]
When attempting to send an html attachment with long lines, sup doesn't seem to encode it to have it accepted by the server.
- sup v0.22.1

**Comment by gauteh** [comment]
This is probably and RMail issue then. Do you have a test-line?

**Comment by dset0x** [comment]
@gauteh 
Sure: `echo {1..5000} > /tmp/foo.html` and then try to attach that.

**Comment by dset0x** [comment]
Nice, thanks!
