### ISSUE TITLE
enhancement: sup should warn about non-continuous source-ids

### ISSUE THREAD

**Issue by inktrap** [sup-heliotrope/sup#492]
Just an idea for an improvement, so a bad config is easier and sooner to find:

sup should warn about non-continuous source-ids.
Reason: sup will run fine without continuous source IDs, but issues like #491 might happen sooner or later. So let's do additional config-checks and throw a warning.

---

References: #491

**Comment by gauteh** [comment]
Valentin Heinz writes on October 20, 2015 20:17:
> Just an idea for an improvement, so a bad config is easier and earlier to find:
> 
> sup should warn about non-continuous source-ids.
> Reason: sup will run fine without continuous source IDs, but issues like #491 might happen sooner or later. So let's do additional config-checks and throw a warning.

Would be nice.

To be specific: the ids need to be unique (not continuous). If you use
sup-add to setup the sources sup will take care of it.

Regards, Gaute

**Comment by inktrap** [comment]
Yes, they need to be unique, as they are ``id``entifiers. Maybe I should reopen #491 
then? If I remove the non-continuous id (5 in my case), isssue #491 won't happen.

**Comment by gauteh** [comment]
Going to close this. This is not a problem if sup-add is used.
