### ISSUE TITLE
Scrolling is slow

### ISSUE THREAD

**Issue by binaryplease** [sup-heliotrope/sup#497]
When I hit the bottom of the thread list and keep scrolling down, scrolling is slow and laggy. 
If I keep the arrow down button pressed, the keypresses "accumulate" and it keeps scrolling down even when the key is released. 
The same happens in the other direction to, when scrolling up again.
Is this only me?

**Comment by gauteh** [comment]
nope, but it probably requires quite a bit of redesign.
