### ISSUE TITLE
Line-wrapped URLs break terminal URL matching

### ISSUE THREAD

**Issue by zevv** [sup-heliotrope/sup#498]
I regularly receive mails with long urls in there (usually containing hashes, uuids and whatever not). Sup line-breaks these URLs if they are longer then the terminal width, but this stops URL detection on most (if not all?) terminal emulators from working.

When cut-and-pasting these URLs there are clearly newlines in there, which of course is the root of the problem.

**Comment by zevv** [comment]
And this one is maybe related: when in thread-view mode, sup does not seem to pick up new terminal sizes when redrawing the window. I first need to go back to inbox-mode and re-open the message for the new window size to be used in the thread-view mode.

I do a lot of terminal resizing (xmonad window manager, using screen to switch between PC and phone, etc), so I run into this many times a day.

**Comment by gauteh** [comment]
Does #241 help?

**Comment by zevv** [comment]
Maybe with some hacks: my sup is running on a remote system over ssh.

**Comment by gauteh** [comment]
Ico Doornekamp writes on December 15, 2015 9:01:
> Maybe with some hacks: my sup is running on a remote system over ssh.

ok. yeah. there is another old issue (by me) regarding a manual re-draw of
the thread-view-mode. I guess terminal re-draw is ok too. maybe a timer,
that checks every second or so.

- g

**Comment by gauteh** [comment]
#178.

**Comment by gauteh** [comment]
is #500 a good enough fix for this?

**Comment by zevv** [comment]
It's a workaround and does the job: it fixes the resizing (but not the
URL wrapping of course, sorry for putting this in the same issue). 

What would be needed to do the same on a SIGWINCH and/or Ctrl-L?

* On 2015-12-18 10:53:26 +0100, Gaute Hope wrote:
 
> is #500 a good enough fix for this?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sup-heliotrope/sup/issues/498#issuecomment-165733648

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by gauteh** [comment]
Not sure, but would be happy to review a PR :)
