### ISSUE TITLE
Contradicting Content-Transfer-Encoding for 7bit and 8bit attachments

### ISSUE THREAD

**Issue by johslarsen** [sup-heliotrope/sup#502]
Attachments that MIME::Types.type_for() determines to be encoded as 7bit or 8bit is given that Content-Transfer-Encoding when they are added (RMail::Message:make_attachment, monkeypatched in /lib/sup/util.rb:88). When the message is sent these parts are rencoded to either quoted-printable or base64 (depending on Content-Type) and during this process the new Content-Transfer-Encoding is appended to the attachment header. The result is an attachment with two contradicting Content-Transfer-Encoding, whose content is encoded as defined by the latter, but interpreted as the former by the clients I have tested (sup and GMail).

The reason why this exact issue occurs is the underlying assumption that RMail::Header#[]= updates the headers, which would have been a intuitive implementation, because that is how it works for hashes. However, this method appends a new key-value pair regardless of whether or not the given key already is defined.

However, another underlying problem with today's implementation is that both RMail::Message:make_attachment and EditMessageMode#transfer_encode is responsible for encoding the content for transfer. 

| Encoding | OK? | RMail::Message:make_attachment | EditMessageMode#transfer_encode |
| --- | --- | --- | --- |
| base64 | + | `[].pack "m"` | ignore |
| quoted-printable | + | `[].pack "M"` | ignore |
| 7bit | - | set Content-Transfer-Encoding | `[].pack "m"` or `[].pack "M"` |
| 8bit | - | set Content-Transfer-Encoding | `[].pack "m"` or `[].pack "M"` |
| nil | + | ignore | `[].pack "m"` or `[].pack "M"` |
| other | +/- | `raise EncodingUnsupportedError` | moot |
#### Steps to reproduce
1. Create new message to yourself
2. Attach something that MIME::Types.type_for() determine to be "7bit" or "8bit" (e.g. .csv)
3. Send message
4. Note multiple Content-Transfer-Encoding when inspecting source of received mail
#### Easy fix

Replace the RMail::Header#[]= calls in EditMessageMode#transfer_encode with #set(), and, if such a hacky fix is desirable, I have a branch where these changes have been tested.
#### Appropriate fix

Delegate the transfer encoding to either RMail::Message:make_attachment or EditMessageMode#transfer_encode (i suggest latter). Additionally I would suggest changing all use of RMail::Header#[]= to either #set or #add, to explicitly communicate whether it should be appended or updated and avoid other, or future, occurrences of the underlying miscommunication issue.

**Comment by danc86** [comment]
Thanks for the detailed bug report. Nearly 10 years later I am fixing this. :-)

In spite of its more general sounding name, the `EditMessageMode#transfer_encode` method is specifically handling re-encoding to ASCII-safe encodings for GPG signing/encrypting. It's only invoked when the message will be signed or encrypted, this bug doesn't affect messages sent in the clear.

Since the method is specifically changing the existing Content-Transfer-Encoding, using `header.set` seems like a reasonable fix, not hacky at all.
