### ISSUE TITLE
Escaping spaces in saved attachment

### ISSUE THREAD

**Issue by ninewise** [sup-heliotrope/sup#505]
When asking for the name when saving an attachment to disk, sup automatically escapes spaces. However, the "file saving part" of sup seems to have no need for the escapes.

Reproduction:
- receive a mail with an attachment called `foo bar.pdf`
- focus the attachment and hit `s`
- sup asks `Save attachment to file or directory: /my/default/dir/foo\ bar.pdf`
- I hit enter
- sup says `Successfully wrote /my/default/dir/foo\ bar.pdf.`
- The file `/my/default/dir/foo\ bar.pdf` is created, while one would expect `/my/default/dir/foo bar.pdf`

How to fix this:
- Either interpret escaping in the filename;
- or, which would actually make sense, don't automatically escape spaces when suggesting the filename.

Additional information:
- sup v0.22.1
- ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
- system: Linux, 4.3.3-2-ARCH #1 SMP PREEMPT Wed Dec 23 20:09:18 CET 2015 x86_64 GNU/Linux

**Comment by ralfebert** [comment]
Same problem here on OS X 10.11:

<img width="200" alt="screen shot 2016-03-11 at 12 11 34" src="https://cloud.githubusercontent.com/assets/26635/13700644/6edc388a-e782-11e5-930d-ed32f043b869.png">
