### ISSUE TITLE
404 for project homepage (supmua.org)

### ISSUE THREAD

**Issue by benjaminfjones** [sup-heliotrope/sup#513]
I get a 404 trying to go to the project homepage, [supmua.org](supmua.org) listed in the README.

**Comment by gauteh** [comment]
Benjamin Jones writes on mai 23, 2016 1:29:
> I get a 404 trying to go to the project homepage, [supmua.org](supmua.org) listed in the README.
> 

Domain is expired, updated to the address:
http://sup-heliotrope.github.io
