### ISSUE TITLE
gemspec homepage's 404 error

### ISSUE THREAD

**Issue by junaruga** [sup-heliotrope/sup#520]
Hi,
I opened the URL that is set on gemspec file homepage, then I got 404 error.
Should we change the URL to new one?
https://github.com/sup-heliotrope/sup/blob/develop/sup.gemspec#L12

http://supmua.org/
404 There isn't a GitHub Pages site here.

Below is looks better as the new URL.
https://rubygems.org/gems/sup

**Comment by gauteh** [comment]
should work now
