### ISSUE TITLE
alter keybindings

### ISSUE THREAD

**Issue by amybruno** [sup-heliotrope/sup#542]
Is there any way to alter the keybindings? 

It would be nice if I could change them to be the same as Inbox's keybindings, since I use both sup and Inbox for different accounts, and it is a little confusing to switch between them

**Comment by terotil** [comment]
Chris Bruno, 2018-02-07 17:08:
> Is there any way to alter the keybindings?

Never tried to do that myself.  There's at least keybindings hook.

From https://github.com/sup-heliotrope/sup/wiki/Hooks

keybindings
-----------
File: ~/.sup/hooks/keybindings.rb
Add custom keybindings.
Methods:
  modes: Hash from mode names to mode classes.
  global_keymap: The top-level keymap.


Example https://github.com/cscorley/dotfiles/blob/master/dots/.sup/hooks/keybindings.rb

modes["inbox-mode"].keymap.add! :archive_and_delete, "Archive and delete", 'd'
modes["thread-index-mode"].keymap.add! :archive_and_delete, "Archive and delete thread", 'd'
modes["thread-view-mode"].keymap.add! :archive_delete_and_next, "Archive, delete, and view next thread", 'd'


To find out what the method names corresponding to current bindings
are, you AFAIK need to look at the source.  Bindings are in
sup/modes/*.rb files and look like this (example from inbox mode).

class InboxMode < ThreadIndexMode
  register_keymap do |k|
    ## overwrite toggle_archived with archive
    k.add :archive, "Archive thread (remove from inbox)", 'a'
    k.add :read_and_archive, "Archive thread (remove from inbox) and mark read", 'A'
    k.add :refine_search, "Refine search", '|'
  end
...


-- 
Tero Tilus ## 050 3635 235 ## http://tero.tilus.net/
