### ISSUE TITLE
Update gem dependency: trollop to optimist

### ISSUE THREAD

**Issue by IPv2** [sup-heliotrope/sup#554]
We currently have a dependency on the gem ```trollop```: https://rubygems.org/gems/trollop

```trollop``` is now deprecated, and renamed to ```optimist```: https://rubygems.org/gems/optimist

Warning visible when installing ```trollop``` gem:
```
!    The 'trollop' gem has been deprecated and has been replaced by 'optimist'.
!    See: https://rubygems.org/gems/optimist
!    And: https://github.com/ManageIQ/optimist
Successfully installed trollop-2.9.10
```

Note: Rename was actioned with Trollop/Optimist release v3.0.0 (2018-08-24). See: https://github.com/ManageIQ/optimist/commit/21de13a56e157b77d52168812e7fcd890cb3e13a

**Comment by danc86** [comment]
It looks like I have been successfully running sup against trollop 2.1.2 which is the version Fedora currently has. Judging by the changelog for optimist, everything should work fine with optimist 3.x as well. I will give it a try.

**Comment by danc86** [comment]
As far as I can see, the only export from trollop was `Trollop` and it's renamed to `Optimist` as expected.

So it looks like a straight substitution `s/trollop/optimist/g s/Trollop/Optimist/g` is working fine. I'll test it out a little more thoroughly later and post a PR.
