### ISSUE TITLE
Redwood::OutOfSyncSourceError from thread: load messages for thread-view-mode

### ISSUE THREAD

**Issue by robert-winkler** [sup-heliotrope/sup#567]
Hi, some threads cause an exception error;
I can't open them and sup crashes. In other clients (e.g. Cypht), the mails seem fine.
I run offlineimap and sup-sync before opening sup.
Any ideas?

Attached the log.

[exception-log.txt](https://github.com/sup-heliotrope/sup/files/4890348/exception-log.txt)

**Comment by IPv2** [comment]
This is normally resolved by `sup-sync`.

What is the output of `sup-sync -v` please?

**Comment by robert-winkler** [comment]
Hi, I think it was due to a renamed or deleted IMAP folder. 
I deleted the .sup/xapian directory and rebuilt it with sup-sync.
Now, the threads work again.
Thanks to all sup maintainers for their great work! 

Excerpts from Iain Parris's message of 2020-07-08 06:05:26 -0700:
> This is normally resolved by `sup-sync`.
> 
> What is the output of `sup-sync -v` please?
>

**Comment by IPv2** [comment]
Good news - thanks @robert-winkler!
