### ISSUE TITLE
Wiki link to home page

### ISSUE THREAD

**Issue by grahamperrin** [sup-heliotrope/sup#597]
<https://github.com/sup-heliotrope/sup/wiki#elsewhere> refers to <http://supmua.org/>, which is no longer used for sup. 

After finding <https://web.archive.org/web/20170224224512/http://supmua.org/> in the Wayback Machine, I assume that the proper home page is: 

<https://sup-heliotrope.github.io/>

**Comment by danc86** [comment]
Thanks for reporting this. Indeed you are right, supmua.org has lapsed so we should link directly to the Github pages site instead. I've updated the wiki and man pages.
